CREATE TABLE [dbo].[CONFIG]
(
[CONFIGID] [int] NOT NULL IDENTITY(1, 1),
[CONFIGNAME] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONFIGVALUE] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONFIG] ADD CONSTRAINT [PK_CONFIG] PRIMARY KEY CLUSTERED  ([CONFIGID]) ON [PRIMARY]
GO
