CREATE TABLE [dbo].[TAGS]
(
[TAGID] [int] NOT NULL IDENTITY(1, 1),
[TAG] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TAGS] ADD CONSTRAINT [PK_TAGS] PRIMARY KEY CLUSTERED  ([TAGID]) ON [PRIMARY]
GO
