CREATE TABLE [dbo].[NEWS]
(
[NEWSID] [int] NOT NULL IDENTITY(1, 1),
[NEWSDATE] [datetime] NULL,
[TITLE] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BODY] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ACTIVE] [bit] NOT NULL CONSTRAINT [DF_NEWS_ACTIVE] DEFAULT ((1)),
[UPDATEDBY] [int] NULL,
[UPDATEDATE] [datetime] NULL,
[LANG] [nchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_NEWS_LANG] DEFAULT ('EN-GB')
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[NEWS] ADD CONSTRAINT [PK_NEWS] PRIMARY KEY CLUSTERED  ([NEWSID]) ON [PRIMARY]
GO
