CREATE TABLE [dbo].[RELATIONSHIPS]
(
[RELID] [int] NOT NULL IDENTITY(1, 1),
[CATEGORYID] [int] NULL,
[RELNAME] [nchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RELDESC] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DISPLAYNAME] [nchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[RELATIONSHIPS] ADD CONSTRAINT [PK_RELATIONSHIPS] PRIMARY KEY CLUSTERED  ([RELID]) ON [PRIMARY]
GO
