CREATE TABLE [dbo].[CASESXPERSONS]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[PERSONID] [int] NOT NULL,
[CASEID] [int] NOT NULL,
[ACTIVE] [int] NULL CONSTRAINT [DF_CASESXPERSONS_ACTIVE] DEFAULT ((1))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CASESXPERSONS] ADD CONSTRAINT [PK_CASESXPERSONS] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
