CREATE TABLE [dbo].[ATTACHMENTS]
(
[ATTACHMENTID] [int] NOT NULL IDENTITY(1, 1),
[DIARYID] [int] NULL,
[TITLE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FILENAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FILEGUID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FILEPATH] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FILEVERSION] [int] NULL,
[CONTENTTYPE] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CMSUSERSRaisedBy] [int] NULL,
[FILESIZE] [int] NULL,
[ACTIVE] [bit] NULL,
[TYPE] [int] NULL CONSTRAINT [DF_ATTACHMENTS_TYPE] DEFAULT ((0)),
[LISTID] [int] NULL CONSTRAINT [DF_ATTACHMENTS_LISTID] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ATTACHMENTS] ADD CONSTRAINT [PK_ATTACHMENTS] PRIMARY KEY CLUSTERED  ([ATTACHMENTID]) ON [PRIMARY]
GO
