CREATE TABLE [dbo].[COUNTRIES]
(
[COUNTRYID] [int] NOT NULL IDENTITY(1, 1),
[ID] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[REGION_NAME] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COUNTRY_NAME] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COUNTRY_CODE] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CURRENCY_NAME] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CURRENCY_CODE] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COUNTRYCODE] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RATE] [numeric] (18, 3) NULL CONSTRAINT [DF_COUNTRIES_RATE] DEFAULT ((0.000)),
[RATEDATE] [datetime] NULL,
[PER] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COUNTRIES] ADD CONSTRAINT [PK_COUNTRIES] PRIMARY KEY CLUSTERED  ([COUNTRYID]) ON [PRIMARY]
GO
