CREATE TABLE [dbo].[SUBSCRIPTIONS]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[SUBSCRIPTIONID] [int] NOT NULL,
[TMROLE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TMSUBNAME] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACTIVE] [bit] NULL CONSTRAINT [DF_SUBSCRIPTIONS_ACTIVE] DEFAULT ((1)),
[DESCRIPTION] [ntext] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[THEMEID] [int] NULL,
[HOMEURL] [nchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SITECODE] [nchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CREATED] [datetime] NULL,
[SITEID] [int] NULL,
[SUBTYPE] [int] NULL CONSTRAINT [DF_SUBSCRIPTIONS_SUBTYPE] DEFAULT ((1)),
[ALIASES] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FLAG1] [bit] NULL,
[FLAG2] [bit] NULL,
[FLAG3] [bit] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[SUBSCRIPTIONS] ADD CONSTRAINT [PK_SUBSCRIPTIONS] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [_dta_index_SUBSCRIPTIONS_7_1015674666__K2_K3] ON [dbo].[SUBSCRIPTIONS] ([SUBSCRIPTIONID], [TMROLE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [_dta_index_SUBSCRIPTIONS_7_1015674666__K2_K3_K1] ON [dbo].[SUBSCRIPTIONS] ([SUBSCRIPTIONID], [TMROLE], [ID]) ON [PRIMARY]
GO
CREATE STATISTICS [_dta_stat_1015674666_3_1] ON [dbo].[SUBSCRIPTIONS] ([TMROLE], [ID])
GO
