CREATE TABLE [dbo].[ACTIONS]
(
[ACTIONID] [int] NOT NULL IDENTITY(1, 1),
[CASEID] [int] NULL,
[TITLE] [varchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_CMSSTATUSOf] [int] NULL CONSTRAINT [DF_ACTIONS__CMSSTATUSOf] DEFAULT ((0)),
[_CMSPRIORITYOf] [int] NULL CONSTRAINT [DF_ACTIONS__CMSPRIORITYOf] DEFAULT ((0)),
[_CMSDATERaised] [datetime] NULL,
[_CMSDATEEnd] [datetime] NULL,
[_CMSDATEEndAgreed] [datetime] NULL,
[_CMSDATEClosed] [datetime] NULL,
[CMSDATELastReminder] [datetime] NULL,
[CMSDATENextReminder] [datetime] NULL,
[_CMSDATEUpdated] [datetime] NULL,
[_CMSUsersUpdated] [int] NULL CONSTRAINT [DF_ACTIONS__CMSUsersUpdated] DEFAULT ((0)),
[_CMSUSERSAssignedBy] [int] NULL CONSTRAINT [DF_ACTIONS__CMSUSERSAssignedBy] DEFAULT ((0)),
[_CMSUSERSManagedBy] [int] NULL CONSTRAINT [DF_ACTIONS__CMSUSERSManagedBy] DEFAULT ((0)),
[_CMSUsersAssignedTo] [int] NULL CONSTRAINT [DF_ACTIONS__CMSUsersAssignedTo] DEFAULT ((0)),
[ActionTypeID] [int] NULL CONSTRAINT [DF_ACTIONS_ActionTypeID] DEFAULT ((0)),
[NoReminder] [bit] NULL CONSTRAINT [DF_ACTIONS_NoReminder] DEFAULT ((0)),
[ACTIVE] [bit] NULL CONSTRAINT [DF_ACTIONS_ACTIVE] DEFAULT ((1)),
[ISISSUE] [bit] NULL CONSTRAINT [DF_ACTIONS_ISISSUE] DEFAULT ((0)),
[_CMSRESOLUTIONSOf] [int] NULL CONSTRAINT [DF_ACTIONS__CMSRESOLUTIONSOf] DEFAULT ((0)),
[_CMSRiskOf] [int] NULL CONSTRAINT [DF_ACTIONS__CMSRiskOf] DEFAULT ((99)),
[_CMSDATEOpened] [datetime] NULL,
[ISSTICKY] [bit] NULL CONSTRAINT [DF_ACTIONS_IsSticky] DEFAULT ((0)),
[_CMSDateOccured] [datetime] NULL,
[_CMSIMPACTOf] [int] NULL CONSTRAINT [DF_ACTIONS__CMSIMPACTOf] DEFAULT ((0)),
[_CMSCAT1OF] [int] NULL CONSTRAINT [DF_ACTIONS__CMSCAT1OF] DEFAULT ((0)),
[_CMSCAT2Of] [int] NULL CONSTRAINT [DF_ACTIONS__CMSCAT2Of] DEFAULT ((0)),
[_CMSCAT3Of] [int] NULL CONSTRAINT [DF_ACTIONS__CMSCAT3Of] DEFAULT ((0)),
[_CMSCAT4Of] [int] NULL CONSTRAINT [DF_ACTIONS__CMSCAT4Of] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACTIONS] ADD CONSTRAINT [PK_Actions] PRIMARY KEY CLUSTERED  ([ACTIONID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [_dta_index_ACTIONS_8_1655676946__K20_K2_K4] ON [dbo].[ACTIONS] ([ISISSUE], [CASEID], [_CMSSTATUSOf]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [_dta_index_ACTIONS_8_1655676946__K20_K2_K1_K16_K30_K29_K28_K27_K26_K22_K13_K4_K5_K14_K12_3_6_7_24] ON [dbo].[ACTIONS] ([ISISSUE], [CASEID], [ACTIONID], [_CMSUsersAssignedTo], [_CMSCAT4Of], [_CMSCAT3Of], [_CMSCAT2Of], [_CMSCAT1OF], [_CMSIMPACTOf], [_CMSRiskOf], [_CMSUsersUpdated], [_CMSSTATUSOf], [_CMSPRIORITYOf], [_CMSUSERSAssignedBy], [_CMSDATEUpdated]) INCLUDE ([_CMSDATEEnd], [_CMSDATERaised], [ISSTICKY], [TITLE]) ON [PRIMARY]
GO
CREATE STATISTICS [_dta_stat_1655676946_4_5_22_26_27_28_29] ON [dbo].[ACTIONS] ([_CMSCAT1OF], [_CMSCAT2Of], [_CMSCAT3Of], [_CMSSTATUSOf], [_CMSPRIORITYOf], [_CMSRiskOf], [_CMSIMPACTOf])
GO
CREATE STATISTICS [_dta_stat_1655676946_20_4_5_22_26_27_28_29] ON [dbo].[ACTIONS] ([_CMSCAT1OF], [_CMSCAT2Of], [_CMSCAT3Of], [ISISSUE], [_CMSSTATUSOf], [_CMSPRIORITYOf], [_CMSRiskOf], [_CMSIMPACTOf])
GO
CREATE STATISTICS [_dta_stat_1655676946_30_29_28_27_26_22_4_5] ON [dbo].[ACTIONS] ([_CMSCAT4Of], [_CMSPRIORITYOf], [_CMSCAT3Of], [_CMSCAT2Of], [_CMSCAT1OF], [_CMSIMPACTOf], [_CMSRiskOf], [_CMSSTATUSOf])
GO
CREATE STATISTICS [_dta_stat_1655676946_12_20] ON [dbo].[ACTIONS] ([_CMSDATEUpdated], [ISISSUE])
GO
CREATE STATISTICS [_dta_stat_1655676946_20_16_13_14_1_2_30_29_28_27_26_22_4] ON [dbo].[ACTIONS] ([_CMSIMPACTOf], [_CMSRiskOf], [_CMSSTATUSOf], [ACTIONID], [CASEID], [_CMSCAT4Of], [_CMSCAT3Of], [_CMSCAT2Of], [_CMSCAT1OF], [ISISSUE], [_CMSUsersAssignedTo], [_CMSUsersUpdated], [_CMSUSERSAssignedBy])
GO
CREATE STATISTICS [_dta_stat_1655676946_1_2_16_30_29_28_27_26_22_13_4_5_14] ON [dbo].[ACTIONS] ([_CMSPRIORITYOf], [_CMSUSERSAssignedBy], [_CMSCAT2Of], [_CMSCAT1OF], [_CMSIMPACTOf], [_CMSRiskOf], [_CMSUsersUpdated], [_CMSSTATUSOf], [ACTIONID], [CASEID], [_CMSUsersAssignedTo], [_CMSCAT4Of], [_CMSCAT3Of])
GO
CREATE STATISTICS [_dta_stat_1655676946_16_13] ON [dbo].[ACTIONS] ([_CMSUsersAssignedTo], [_CMSUsersUpdated])
GO
CREATE STATISTICS [_dta_stat_1655676946_13_14_16] ON [dbo].[ACTIONS] ([_CMSUsersUpdated], [_CMSUSERSAssignedBy], [_CMSUsersAssignedTo])
GO
CREATE STATISTICS [_dta_stat_1655676946_20_30_29_28_27_26_22_4_5_1_2_16_13_14_12] ON [dbo].[ACTIONS] ([ACTIONID], [CASEID], [_CMSUsersAssignedTo], [_CMSUsersUpdated], [_CMSUSERSAssignedBy], [_CMSDATEUpdated], [_CMSCAT2Of], [_CMSCAT1OF], [_CMSIMPACTOf], [_CMSRiskOf], [_CMSSTATUSOf], [_CMSPRIORITYOf], [ISISSUE], [_CMSCAT4Of], [_CMSCAT3Of])
GO
CREATE STATISTICS [_dta_stat_1655676946_2_4] ON [dbo].[ACTIONS] ([CASEID], [_CMSSTATUSOf])
GO
CREATE STATISTICS [_dta_stat_1655676946_2_4_20] ON [dbo].[ACTIONS] ([CASEID], [_CMSSTATUSOf], [ISISSUE])
GO
CREATE STATISTICS [_dta_stat_1655676946_2_20_4] ON [dbo].[ACTIONS] ([CASEID], [ISISSUE], [_CMSSTATUSOf])
GO
CREATE STATISTICS [_dta_stat_1655676946_20_13_14] ON [dbo].[ACTIONS] ([ISISSUE], [_CMSUsersUpdated], [_CMSUSERSAssignedBy])
GO
CREATE STATISTICS [_dta_stat_1655676946_20_1] ON [dbo].[ACTIONS] ([ISISSUE], [ACTIONID])
GO
CREATE STATISTICS [_dta_stat_1655676946_20_2] ON [dbo].[ACTIONS] ([ISISSUE], [CASEID])
GO
