CREATE TABLE [dbo].[TEMPLATES]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[TEMPLATEID] [int] NOT NULL,
[TEMPLATENAME] [nchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SUBSCRIPTION] [int] NULL,
[GLOBAL] [bit] NULL CONSTRAINT [DF_TEMPLATES_GLOBAL] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TEMPLATES] ADD CONSTRAINT [PK_TEMPLATES_1] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
