CREATE TABLE [dbo].[USERSEXTENDED]
(
[USERID] [int] NOT NULL,
[IsISManager] [bit] NOT NULL CONSTRAINT [DF_USERSEXTENDED_IsISManager] DEFAULT ((0)),
[IsTMManager] [bit] NOT NULL CONSTRAINT [DF_USERSEXTENDED_IsTMManager] DEFAULT ((0)),
[IsTMAdmin] [bit] NOT NULL CONSTRAINT [DF_USERSEXTENDED_IsTMAdmin] DEFAULT ((0)),
[AgencyID] [int] NOT NULL CONSTRAINT [DF_USERSEXTENDED_AgencyID] DEFAULT ((0)),
[IsDetective] [bit] NOT NULL CONSTRAINT [DF_USERSEXTENDED_IsDetective] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[USERSEXTENDED] ADD CONSTRAINT [PK_USERSEXTENDED] PRIMARY KEY CLUSTERED  ([USERID]) ON [PRIMARY]
GO
