CREATE TABLE [dbo].[CATEGORIES]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[CATEGORYID] [int] NOT NULL,
[TEMPLATEID] [int] NULL,
[CATNAME] [nchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DISPLAYNAME] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CATEGORIES_DISPLAYNAME] DEFAULT ('   '),
[CATDESC] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CATOF] [nchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CATOFFIELDNAME] [nchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ATTNO] [int] NULL,
[ATTNAME1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ATTNAME2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ATTNAME3] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ATTNAME4] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ATTNAME5] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ATTNAME6] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ATTNAMETAG] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ATTNAMETEXT] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ATTNAMEID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACTIVE] [bit] NOT NULL,
[ATTRELNO] [int] NULL,
[ATTRELID] [int] NULL,
[RENDERTOLEVEL] [int] NULL,
[LEAFATLEVEL] [int] NULL,
[LANGUAGE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TERMS] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ISGLOBAL] [bit] NULL CONSTRAINT [DF_CATEGORIES_ISGLOBAL] DEFAULT ((0)),
[ISADMIN] [bit] NOT NULL CONSTRAINT [DF_CATEGORIES_ISADMIN] DEFAULT ((0))
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[CATEGORIES] ADD CONSTRAINT [PK_CATEGORIES_3] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [_dta_index_CATEGORIES_7_1470341444__K3_K2_K4] ON [dbo].[CATEGORIES] ([TEMPLATEID], [CATEGORYID], [CATNAME]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [_dta_index_CATEGORIES_7_1470341444__K3_K2_K4_K8_K22_K24_K25_K26_K27] ON [dbo].[CATEGORIES] ([TEMPLATEID], [CATEGORYID], [CATNAME], [CATOFFIELDNAME], [RENDERTOLEVEL], [LANGUAGE], [TERMS], [ISGLOBAL], [ISADMIN]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [_dta_index_CATEGORIES_7_1470341444__K3_K4_K2_K8_K9_K10_K11_K12_K13_K19_K20_K21_6_7_22_23_24_25_26_27] ON [dbo].[CATEGORIES] ([TEMPLATEID], [CATNAME], [CATEGORYID], [CATOFFIELDNAME], [ATTNO], [ATTNAME1], [ATTNAME2], [ATTNAME3], [ATTNAME4], [ACTIVE], [ATTRELNO], [ATTRELID]) INCLUDE ([CATDESC], [CATOF], [ISADMIN], [ISGLOBAL], [LANGUAGE], [LEAFATLEVEL], [RENDERTOLEVEL], [TERMS]) ON [PRIMARY]
GO
CREATE STATISTICS [_dta_stat_1470341444_4_2_8_9_10_11_12_13_19_20_21_7] ON [dbo].[CATEGORIES] ([CATNAME], [CATEGORYID], [CATOFFIELDNAME], [ATTNO], [ATTRELID], [CATOF], [ATTNAME1], [ATTNAME2], [ATTNAME3], [ATTNAME4], [ACTIVE], [ATTRELNO])
GO
CREATE STATISTICS [_dta_stat_1470341444_4_8_22_24_25_26_27] ON [dbo].[CATEGORIES] ([CATNAME], [CATOFFIELDNAME], [RENDERTOLEVEL], [LANGUAGE], [TERMS], [ISGLOBAL], [ISADMIN])
GO
CREATE STATISTICS [_dta_stat_1470341444_2_3_4_8_22_24_25_26_27] ON [dbo].[CATEGORIES] ([RENDERTOLEVEL], [LANGUAGE], [TERMS], [ISGLOBAL], [ISADMIN], [CATEGORYID], [TEMPLATEID], [CATNAME], [CATOFFIELDNAME])
GO
