CREATE TABLE [dbo].[LISTHEADERS]
(
[LISTHEADERID] [int] NOT NULL IDENTITY(1, 1),
[TITLE] [nchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DESCRIPTION] [nvarchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CASEID] [int] NOT NULL,
[ACTIONID] [int] NOT NULL,
[SHEETNO] [int] NOT NULL,
[SHEETNAME] [nchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHEETTYPE] [int] NOT NULL CONSTRAINT [DF_LISTHEADERS_SHEETTYPE] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LISTHEADERS] ADD CONSTRAINT [PK_LISTHEADERS] PRIMARY KEY CLUSTERED  ([LISTHEADERID]) ON [PRIMARY]
GO
