CREATE TABLE [dbo].[THEMES]
(
[THEMEID] [int] NOT NULL IDENTITY(1, 1),
[THEMETYPE] [int] NULL CONSTRAINT [DF_THEMES_THEMETYPE] DEFAULT ((0)),
[SUBSCRIPTIONID] [int] NULL CONSTRAINT [DF_THEMES_SUBSCRIPTIONID] DEFAULT ((0)),
[Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[color1] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[color2] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[color3] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[color4] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[color5] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[color6] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[color7] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[color8] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[color9] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[color10] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HeadeBackColor] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[text1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[text2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[text3] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[text4] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[text5] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LogoTitle1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LogoTitle2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IconFile] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LogoFile] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LogoFileOther] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[color11] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[color12] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[color13] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[color14] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[color15] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[text6] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[text7] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[text8] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[text9] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[text10] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Color16] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[color17] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[color18] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[color19] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[color20] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[color21] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[color22] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[color23] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[color24] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[color25] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gColor1] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gColor2] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gColor3] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gColor4] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gColor5] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gColor6] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gColor7] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gColor8] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gColor9] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gColor10] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gColor11] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gColor12] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gColor13] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gColor14] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gColor15] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[THEMES] ADD CONSTRAINT [PK_THEMES] PRIMARY KEY CLUSTERED  ([THEMEID]) ON [PRIMARY]
GO
