CREATE TABLE [dbo].[CASES]
(
[CASEID] [int] NOT NULL IDENTITY(1, 1),
[REFERENCE] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CASES_REFERENCE] DEFAULT ('None'),
[ISSTICKY] [bit] NOT NULL,
[SUBSCRIPTIONID] [int] NULL,
[HELPINGSUBSCRIPTIONID] [int] NULL CONSTRAINT [DF_CASES_HELPINGSUBSCRIPTIONID] DEFAULT ((31)),
[TITLE] [nvarchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ISUNMANAGED] [bit] NULL CONSTRAINT [DF_CASES_ISUNMANAGED] DEFAULT ((0)),
[_CMSPRODUCTCONTAINS] [int] NULL CONSTRAINT [DF_CASES__CMSPRODUCTCONTAINS] DEFAULT ((0)),
[_CMSPROJECTCONTAINS] [int] NULL CONSTRAINT [DF_CASES__CMSPROJECTCONTAINS] DEFAULT ((0)),
[_CMSPRIORITYOF] [int] NULL CONSTRAINT [DF_CASES__CMSPRIORITYOF] DEFAULT ((0)),
[_CMSSTATUSOF] [int] NULL CONSTRAINT [DF_CASES__CMSSTATUSOF] DEFAULT ((0)),
[REPORTEDBY] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CASES_REPORTEDBY] DEFAULT ('None'),
[_CMSDATEOCCURED] [datetime] NULL,
[_CMSDATERAISED] [datetime] NULL,
[_CMSDATEUPDATED] [datetime] NULL,
[_CMSDATEEND] [datetime] NULL,
[_CMSDATEENDAGREED] [datetime] NULL,
[ACTIVE] [smallint] NULL CONSTRAINT [DF_CASES_ACTIVE] DEFAULT ((1)),
[_CMSUSERSRAISEDBY] [int] NULL CONSTRAINT [DF_CASES__CMSUSERSRAISEDBY] DEFAULT ((0)),
[_CMSUSERSUPDATED] [int] NULL CONSTRAINT [DF_CASES__CMSUSERSUPDATED] DEFAULT ((0)),
[_CMSUSERSMANAGEDBY] [int] NULL CONSTRAINT [DF_CASES__CMSUSERSMANAGEDBY] DEFAULT ((0)),
[_CMSUSERSASSIGNEDBY] [int] NULL CONSTRAINT [DF_CASES__CMSUSERSASSIGNEDBY] DEFAULT ((0)),
[_CMSUSERSASSIGNEDTO] [int] NULL CONSTRAINT [DF_CASES__CMSUSERSASSIGNEDTO] DEFAULT ((0)),
[LastUpdatedBy] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CASES_LastUpdatedBy] DEFAULT ('None'),
[_CMSDATEClosed] [datetime] NULL,
[_CMSRESOLUTIONSOf] [int] NULL CONSTRAINT [DF_CASES__CMSRESOLUTIONSOf] DEFAULT ((0)),
[GROUPID] [int] NULL CONSTRAINT [DF_CASES_GROUPID] DEFAULT ((0)),
[ID] [int] NULL CONSTRAINT [DF_CASES_ID] DEFAULT ((0)),
[ACTIONID] [int] NULL CONSTRAINT [DF_CASES_ACTIONID] DEFAULT ((0)),
[ISISSUE] [bit] NOT NULL CONSTRAINT [DF_CASES_ISISSUE] DEFAULT ((0)),
[_CMSIMPACTOF] [int] NULL CONSTRAINT [DF_CASES__CMSIMPACTOF] DEFAULT ((0)),
[_CMSRISKOF] [int] NULL CONSTRAINT [DF_CASES__CMSRISKOF] DEFAULT ((0)),
[_CMSLOCATIONSRAISEDBY] [int] NULL CONSTRAINT [DF_CASES__CMSLOCATIONSRAISEDBY] DEFAULT ((0)),
[_CMSCAT0OF] [int] NULL CONSTRAINT [DF_CASES__CMSCAT0OF] DEFAULT ((0)),
[_CMSCAT1OF] [int] NULL CONSTRAINT [DF_CASES__CMSCAT1OF] DEFAULT ((0)),
[_CMSCAT2OF] [int] NULL CONSTRAINT [DF_CASES__CMSCAT2OF] DEFAULT ((0)),
[_CMSCAT3OF] [int] NULL CONSTRAINT [DF_CASES__CMSCAT3OF] DEFAULT ((0)),
[_CMSCAT4Of] [int] NULL CONSTRAINT [DF_CASES__CMSCAT4Of] DEFAULT ((0)),
[_CMSCAT5Of] [int] NULL CONSTRAINT [DF_CASES__CMSCAT5Of] DEFAULT ((0)),
[_CMSCAT6Of] [int] NULL CONSTRAINT [DF_CASES__CMSCAT6Of] DEFAULT ((0)),
[_CMSCAT7Of] [int] NULL CONSTRAINT [DF_CASES__CMSCAT7Of] DEFAULT ((0)),
[_CMSCAT8Of] [int] NULL CONSTRAINT [DF_CASES__CMSCAT8Of] DEFAULT ((0)),
[_CMSCAT9Of] [int] NULL CONSTRAINT [DF_CASES__CMSCAT9Of] DEFAULT ((0)),
[_CMSCAT10Of] [int] NULL CONSTRAINT [DF_CASES__CMSCAT10Of] DEFAULT ((0)),
[Origin] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Country] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Destination] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Declared_USD] [decimal] (18, 2) NULL,
[Declared_EUR] [decimal] (18, 2) NULL,
[_CMSLOCATIONSDELIVERTO] [int] NULL CONSTRAINT [DF_CASES__CMSLOCATIONSDELIVERTO] DEFAULT ((0)),
[IDOLD] [int] NULL,
[Number1] [int] NULL,
[EVENTDESCRIPTION] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FILENO] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CASES_FILENO] DEFAULT (' '),
[RECOVEREDVALUE] [decimal] (18, 2) NULL CONSTRAINT [DF_CASES_RECOVEREDVALUE] DEFAULT ((0)),
[TOTALVALUE] [decimal] (18, 2) NULL CONSTRAINT [DF_CASES_TOTALVALUE] DEFAULT ((0)),
[EVENTTIME] [time] NULL,
[EVENTDATE] [datetime] NULL,
[ISFLAG1] [bit] NULL CONSTRAINT [DF_CASES_ISFLAG1] DEFAULT ((0)),
[ISFLAG2] [bit] NULL CONSTRAINT [DF_CASES_ISFLAG2] DEFAULT ((0)),
[REFERENCE1] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CASES_REFERENCE1] DEFAULT (' '),
[REFERENCE2] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CASES_REFERENCE2] DEFAULT (' '),
[REFERENCE3] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CASES_REFERENCE3] DEFAULT (' '),
[REFERENCE4] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CASES_REFERENCE4] DEFAULT (' '),
[REFERENCE5] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CASES_REFERENCE5] DEFAULT (' '),
[REFERENCE6] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CASES_REFERENCE6] DEFAULT (' '),
[PREVENTEDVALUE] [decimal] (18, 2) NULL CONSTRAINT [DF_CASES_PREVENTEDVALUE] DEFAULT ((0)),
[EXTLOCATION] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXTLOCATIONLINE1] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXTLOCATIONLINE2] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXTLOCATIONLINE3] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXTLOCATIONLINE4] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ISKNOWN] [bit] NULL CONSTRAINT [DF_CASES_ISKNOWN] DEFAULT ((0)),
[ISFLAG3] [bit] NULL,
[ISFLAG4] [bit] NULL,
[ISFLAG5] [bit] NULL,
[ISFLAG6] [bit] NULL,
[DESCRIPTION1] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DESCRIPTION2] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DESCRIPTION3] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DESCRIPTION4] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ABSENTDATE] [datetime] NULL,
[ABSENTTIME] [time] NULL,
[NO1] [int] NULL,
[NO2] [int] NULL,
[DESCRIPTION5] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DESCRIPTION6] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DESCRIPTION7] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[CASES] ADD CONSTRAINT [PK_CASES] PRIMARY KEY NONCLUSTERED  ([CASEID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [_dta_index_CASES_8_1857441691__K15D_K4_K1_2_3_6_7_8_9_10_11_12_13_14_16_19_20_21_22_23_27_31_32_33_35_36_37_38_39_40_41_42_43_] ON [dbo].[CASES] ([_CMSDATEUPDATED] DESC, [SUBSCRIPTIONID], [CASEID]) INCLUDE ([_CMSCAT10Of], [_CMSCAT1OF], [_CMSCAT2OF], [_CMSCAT3OF], [_CMSCAT4Of], [_CMSCAT5Of], [_CMSCAT6Of], [_CMSCAT7Of], [_CMSCAT8Of], [_CMSCAT9Of], [_CMSDATEEND], [_CMSDATEOCCURED], [_CMSDATERAISED], [_CMSIMPACTOF], [_CMSLOCATIONSDELIVERTO], [_CMSLOCATIONSRAISEDBY], [_CMSPRIORITYOF], [_CMSPRODUCTCONTAINS], [_CMSPROJECTCONTAINS], [_CMSRISKOF], [_CMSSTATUSOF], [_CMSUSERSASSIGNEDBY], [_CMSUSERSASSIGNEDTO], [_CMSUSERSMANAGEDBY], [_CMSUSERSRAISEDBY], [_CMSUSERSUPDATED], [GROUPID], [ISSTICKY], [ISUNMANAGED], [REFERENCE], [REPORTEDBY], [TITLE]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [CASEID] ON [dbo].[CASES] ([CASEID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [_dta_index_CASES_8_1857441691__K1_K37_K35_K38_K39_K9_K10_K11_K27_K26_K36_K8_K31_K32_K33_K50_2_3_4_6_7_12_13_14_15_16_19_20_21_] ON [dbo].[CASES] ([CASEID], [_CMSCAT3OF], [_CMSCAT1OF], [_CMSCAT4Of], [_CMSCAT5Of], [_CMSPROJECTCONTAINS], [_CMSPRIORITYOF], [_CMSSTATUSOF], [GROUPID], [_CMSRESOLUTIONSOf], [_CMSCAT2OF], [_CMSPRODUCTCONTAINS], [_CMSIMPACTOF], [_CMSRISKOF], [_CMSLOCATIONSRAISEDBY], [_CMSLOCATIONSDELIVERTO]) INCLUDE ([_CMSDATEEND], [_CMSDATEOCCURED], [_CMSDATERAISED], [_CMSDATEUPDATED], [_CMSUSERSASSIGNEDBY], [_CMSUSERSASSIGNEDTO], [_CMSUSERSMANAGEDBY], [_CMSUSERSRAISEDBY], [_CMSUSERSUPDATED], [ISSTICKY], [ISUNMANAGED], [REFERENCE], [REPORTEDBY], [SUBSCRIPTIONID], [TITLE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [CaseFilter] ON [dbo].[CASES] ([CASEID], [_CMSDATEUPDATED], [_CMSSTATUSOF]) ON [PRIMARY]
GO
CREATE CLUSTERED INDEX [_dta_index_CASES_c_8_1857441691__K1_K23_K50_K33_K22_K21_K20_K19_K32_K31_K8_K36_K26_K27_K11] ON [dbo].[CASES] ([CASEID], [_CMSUSERSASSIGNEDTO], [_CMSLOCATIONSDELIVERTO], [_CMSLOCATIONSRAISEDBY], [_CMSUSERSASSIGNEDBY], [_CMSUSERSMANAGEDBY], [_CMSUSERSUPDATED], [_CMSUSERSRAISEDBY], [_CMSRISKOF], [_CMSIMPACTOF], [_CMSPRODUCTCONTAINS], [_CMSCAT2OF], [_CMSRESOLUTIONSOf], [GROUPID], [_CMSSTATUSOF]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [_dta_index_CASES_8_1857441691__K1_K4] ON [dbo].[CASES] ([CASEID], [SUBSCRIPTIONID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [_dta_index_CASES_8_1857441691__K4_K14_1_2_6_7_8_9_10_11_12_13_15_16_19_20_21_22_23_27_31_32_33_35_36_37_38_39_40_41_42_43_44_50] ON [dbo].[CASES] ([SUBSCRIPTIONID], [_CMSDATERAISED]) INCLUDE ([_CMSCAT10Of], [_CMSCAT1OF], [_CMSCAT2OF], [_CMSCAT3OF], [_CMSCAT4Of], [_CMSCAT5Of], [_CMSCAT6Of], [_CMSCAT7Of], [_CMSCAT8Of], [_CMSCAT9Of], [_CMSDATEEND], [_CMSDATEOCCURED], [_CMSDATEUPDATED], [_CMSIMPACTOF], [_CMSLOCATIONSDELIVERTO], [_CMSLOCATIONSRAISEDBY], [_CMSPRIORITYOF], [_CMSPRODUCTCONTAINS], [_CMSPROJECTCONTAINS], [_CMSRISKOF], [_CMSSTATUSOF], [_CMSUSERSASSIGNEDBY], [_CMSUSERSASSIGNEDTO], [_CMSUSERSMANAGEDBY], [_CMSUSERSRAISEDBY], [_CMSUSERSUPDATED], [CASEID], [GROUPID], [ISUNMANAGED], [REFERENCE], [REPORTEDBY], [TITLE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [_dta_index_CASES_8_1857441691__K4_K10_K21_K40_K11_K1_K19_K22_K31_K35_K36_K37_K38_K9_K32_K39_8_20_23_27_33_41_42_43_44_50] ON [dbo].[CASES] ([SUBSCRIPTIONID], [_CMSPRIORITYOF], [_CMSUSERSMANAGEDBY], [_CMSCAT6Of], [_CMSSTATUSOF], [CASEID], [_CMSUSERSRAISEDBY], [_CMSUSERSASSIGNEDBY], [_CMSIMPACTOF], [_CMSCAT1OF], [_CMSCAT2OF], [_CMSCAT3OF], [_CMSCAT4Of], [_CMSPROJECTCONTAINS], [_CMSRISKOF], [_CMSCAT5Of]) INCLUDE ([_CMSCAT10Of], [_CMSCAT7Of], [_CMSCAT8Of], [_CMSCAT9Of], [_CMSLOCATIONSDELIVERTO], [_CMSLOCATIONSRAISEDBY], [_CMSPRODUCTCONTAINS], [_CMSUSERSASSIGNEDTO], [_CMSUSERSUPDATED], [GROUPID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [_dta_index_CASES_7_1455304940__K4_K11_K32_K19_K27_K22_K50_K20_K36_K23_K1_K31_K26_K33_K8_K21_2_12_14_48_49] ON [dbo].[CASES] ([SUBSCRIPTIONID], [_CMSSTATUSOF], [_CMSRISKOF], [_CMSUSERSRAISEDBY], [GROUPID], [_CMSUSERSASSIGNEDBY], [_CMSLOCATIONSDELIVERTO], [_CMSUSERSUPDATED], [_CMSCAT2OF], [_CMSUSERSASSIGNEDTO], [CASEID], [_CMSIMPACTOF], [_CMSRESOLUTIONSOf], [_CMSLOCATIONSRAISEDBY], [_CMSPRODUCTCONTAINS], [_CMSUSERSMANAGEDBY]) INCLUDE ([_CMSDATERAISED], [Declared_EUR], [Declared_USD], [REFERENCE], [REPORTEDBY]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [_dta_index_CASES_8_1857441691__K4_K1_K37_K35_K38_K39_K9_K10_K11_K27_K26_K36_K8_K31_K32_K19_20_21_22_23_33_50] ON [dbo].[CASES] ([SUBSCRIPTIONID], [CASEID], [_CMSCAT3OF], [_CMSCAT1OF], [_CMSCAT4Of], [_CMSCAT5Of], [_CMSPROJECTCONTAINS], [_CMSPRIORITYOF], [_CMSSTATUSOF], [GROUPID], [_CMSRESOLUTIONSOf], [_CMSCAT2OF], [_CMSPRODUCTCONTAINS], [_CMSIMPACTOF], [_CMSRISKOF], [_CMSUSERSRAISEDBY]) INCLUDE ([_CMSLOCATIONSDELIVERTO], [_CMSLOCATIONSRAISEDBY], [_CMSUSERSASSIGNEDBY], [_CMSUSERSASSIGNEDTO], [_CMSUSERSMANAGEDBY], [_CMSUSERSUPDATED]) ON [PRIMARY]
GO
CREATE STATISTICS [_dta_stat_1455304940_36_4_1_23_50_33_22_21_20_19_32_31_8_26_27] ON [dbo].[CASES] ([_CMSCAT2OF], [SUBSCRIPTIONID], [CASEID], [_CMSUSERSRAISEDBY], [_CMSRISKOF], [_CMSIMPACTOF], [_CMSPRODUCTCONTAINS], [_CMSRESOLUTIONSOf], [GROUPID], [_CMSUSERSASSIGNEDTO], [_CMSLOCATIONSDELIVERTO], [_CMSLOCATIONSRAISEDBY], [_CMSUSERSASSIGNEDBY], [_CMSUSERSMANAGEDBY], [_CMSUSERSUPDATED])
GO
CREATE STATISTICS [_dta_stat_1455304940_31_36_4_1_23_50_33_22_21_20_19] ON [dbo].[CASES] ([_CMSIMPACTOF], [_CMSCAT2OF], [SUBSCRIPTIONID], [_CMSUSERSUPDATED], [_CMSUSERSRAISEDBY], [CASEID], [_CMSUSERSASSIGNEDTO], [_CMSLOCATIONSDELIVERTO], [_CMSLOCATIONSRAISEDBY], [_CMSUSERSASSIGNEDBY], [_CMSUSERSMANAGEDBY])
GO
CREATE STATISTICS [_dta_stat_1455304940_36_11_32_19_27_22_50] ON [dbo].[CASES] ([_CMSLOCATIONSDELIVERTO], [_CMSCAT2OF], [_CMSSTATUSOF], [_CMSRISKOF], [_CMSUSERSRAISEDBY], [GROUPID], [_CMSUSERSASSIGNEDBY])
GO
CREATE STATISTICS [_dta_stat_1455304940_50_36_4_1] ON [dbo].[CASES] ([_CMSLOCATIONSDELIVERTO], [_CMSCAT2OF], [SUBSCRIPTIONID], [CASEID])
GO
CREATE STATISTICS [_dta_stat_1455304940_33_36_4_1_23_50_22_21] ON [dbo].[CASES] ([_CMSLOCATIONSRAISEDBY], [_CMSCAT2OF], [SUBSCRIPTIONID], [CASEID], [_CMSUSERSASSIGNEDTO], [_CMSLOCATIONSDELIVERTO], [_CMSUSERSASSIGNEDBY], [_CMSUSERSMANAGEDBY])
GO
CREATE STATISTICS [_dta_stat_1455304940_8_36_4_1_23_50_33_22_21_20_19_32] ON [dbo].[CASES] ([_CMSPRODUCTCONTAINS], [_CMSCAT2OF], [SUBSCRIPTIONID], [_CMSUSERSUPDATED], [_CMSUSERSRAISEDBY], [_CMSRISKOF], [CASEID], [_CMSUSERSASSIGNEDTO], [_CMSLOCATIONSDELIVERTO], [_CMSLOCATIONSRAISEDBY], [_CMSUSERSASSIGNEDBY], [_CMSUSERSMANAGEDBY])
GO
CREATE STATISTICS [_dta_stat_1455304940_26_36_4_1_23_50_33_22_21_20_19_32_31] ON [dbo].[CASES] ([_CMSRESOLUTIONSOf], [_CMSCAT2OF], [_CMSUSERSMANAGEDBY], [_CMSUSERSUPDATED], [_CMSUSERSRAISEDBY], [_CMSRISKOF], [_CMSIMPACTOF], [SUBSCRIPTIONID], [CASEID], [_CMSUSERSASSIGNEDTO], [_CMSLOCATIONSDELIVERTO], [_CMSLOCATIONSRAISEDBY], [_CMSUSERSASSIGNEDBY])
GO
CREATE STATISTICS [_dta_stat_1455304940_32_36_4_1_23_50_33_22_21_20] ON [dbo].[CASES] ([_CMSRISKOF], [_CMSCAT2OF], [SUBSCRIPTIONID], [_CMSUSERSUPDATED], [CASEID], [_CMSUSERSASSIGNEDTO], [_CMSLOCATIONSDELIVERTO], [_CMSLOCATIONSRAISEDBY], [_CMSUSERSASSIGNEDBY], [_CMSUSERSMANAGEDBY])
GO
CREATE STATISTICS [_dta_stat_1455304940_11_32_19_27_22_50_20_36_23_1_31_26_33_8_21_4] ON [dbo].[CASES] ([_CMSSTATUSOF], [_CMSPRODUCTCONTAINS], [_CMSUSERSMANAGEDBY], [SUBSCRIPTIONID], [_CMSCAT2OF], [_CMSUSERSASSIGNEDTO], [CASEID], [_CMSIMPACTOF], [_CMSRESOLUTIONSOf], [_CMSLOCATIONSRAISEDBY], [_CMSRISKOF], [_CMSUSERSRAISEDBY], [GROUPID], [_CMSUSERSASSIGNEDBY], [_CMSLOCATIONSDELIVERTO], [_CMSUSERSUPDATED])
GO
CREATE STATISTICS [_dta_stat_1455304940_22_23_19_20_21_11_32_27_50_36_1_31_26_33] ON [dbo].[CASES] ([_CMSUSERSASSIGNEDBY], [_CMSLOCATIONSRAISEDBY], [GROUPID], [_CMSLOCATIONSDELIVERTO], [_CMSCAT2OF], [CASEID], [_CMSIMPACTOF], [_CMSRESOLUTIONSOf], [_CMSUSERSASSIGNEDTO], [_CMSUSERSRAISEDBY], [_CMSUSERSUPDATED], [_CMSUSERSMANAGEDBY], [_CMSSTATUSOF], [_CMSRISKOF])
GO
CREATE STATISTICS [_dta_stat_1455304940_23_36_4] ON [dbo].[CASES] ([_CMSUSERSASSIGNEDTO], [_CMSCAT2OF], [SUBSCRIPTIONID])
GO
CREATE STATISTICS [_dta_stat_1455304940_21_36_4_1_23_50_33] ON [dbo].[CASES] ([_CMSUSERSMANAGEDBY], [_CMSCAT2OF], [SUBSCRIPTIONID], [CASEID], [_CMSUSERSASSIGNEDTO], [_CMSLOCATIONSDELIVERTO], [_CMSLOCATIONSRAISEDBY])
GO
CREATE STATISTICS [_dta_stat_1455304940_19_36_4_1_23_50_33_22_21] ON [dbo].[CASES] ([_CMSUSERSRAISEDBY], [_CMSUSERSASSIGNEDBY], [_CMSUSERSMANAGEDBY], [_CMSCAT2OF], [SUBSCRIPTIONID], [CASEID], [_CMSUSERSASSIGNEDTO], [_CMSLOCATIONSDELIVERTO], [_CMSLOCATIONSRAISEDBY])
GO
CREATE STATISTICS [_dta_stat_1455304940_20_36_4_1_23_50_33_22_21_19_32_31_8_26_11] ON [dbo].[CASES] ([_CMSUSERSUPDATED], [_CMSCAT2OF], [SUBSCRIPTIONID], [_CMSUSERSRAISEDBY], [_CMSRISKOF], [_CMSIMPACTOF], [_CMSPRODUCTCONTAINS], [_CMSRESOLUTIONSOf], [_CMSSTATUSOF], [CASEID], [_CMSUSERSASSIGNEDTO], [_CMSLOCATIONSDELIVERTO], [_CMSLOCATIONSRAISEDBY], [_CMSUSERSASSIGNEDBY], [_CMSUSERSMANAGEDBY])
GO
CREATE STATISTICS [_dta_stat_1455304940_1_11_32_19_27_22_50_20_36] ON [dbo].[CASES] ([CASEID], [_CMSSTATUSOF], [_CMSRISKOF], [_CMSUSERSRAISEDBY], [GROUPID], [_CMSUSERSASSIGNEDBY], [_CMSLOCATIONSDELIVERTO], [_CMSUSERSUPDATED], [_CMSCAT2OF])
GO
CREATE STATISTICS [_dta_stat_1455304940_27_36_4_1_23_50_33_22_21_20_19_32_31_8_11] ON [dbo].[CASES] ([GROUPID], [_CMSCAT2OF], [SUBSCRIPTIONID], [CASEID], [_CMSUSERSRAISEDBY], [_CMSRISKOF], [_CMSIMPACTOF], [_CMSPRODUCTCONTAINS], [_CMSSTATUSOF], [_CMSUSERSASSIGNEDTO], [_CMSLOCATIONSDELIVERTO], [_CMSLOCATIONSRAISEDBY], [_CMSUSERSASSIGNEDBY], [_CMSUSERSMANAGEDBY], [_CMSUSERSUPDATED])
GO
CREATE FULLTEXT INDEX ON [dbo].[CASES] KEY INDEX [CASEID] ON [CASES]
GO
ALTER FULLTEXT INDEX ON [dbo].[CASES] ADD ([REFERENCE] LANGUAGE 1033)
GO
ALTER FULLTEXT INDEX ON [dbo].[CASES] ADD ([TITLE] LANGUAGE 1033)
GO
ALTER FULLTEXT INDEX ON [dbo].[CASES] ADD ([REPORTEDBY] LANGUAGE 1033)
GO
