CREATE TABLE [dbo].[SUBSXUSERS]
(
[SUBID] [int] NOT NULL IDENTITY(1, 1),
[SUBSCRIPTIONID] [int] NOT NULL,
[USERID] [int] NOT NULL,
[ISSUBMANAGER] [bit] NOT NULL CONSTRAINT [DF_SUBSXUSERS_IsSubManager] DEFAULT ((0)),
[ACTIVE] [bit] NULL CONSTRAINT [DF_SUBSXUSERS_ACTIVE] DEFAULT ((1))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SUBSXUSERS] ADD CONSTRAINT [PK_SUBSXUSERS] PRIMARY KEY CLUSTERED  ([SUBID]) ON [PRIMARY]
GO
