CREATE TABLE [dbo].[CABINET]
(
[CABINETID] [int] NOT NULL IDENTITY(1, 1),
[TITLE] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DESCRIPTION] [nvarchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONTENTID] [int] NULL CONSTRAINT [DF_CABINET_CONTENTID] DEFAULT ((0)),
[ITEMTYPE] [nchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CABINET_ITEMTYPE] DEFAULT (N'File'),
[CASEID] [int] NOT NULL,
[ACTIONID] [int] NULL,
[ITEMSUBTYPE] [nchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CABINET_ITEMSUBTYPE] DEFAULT (' '),
[ITEMTYPENO] [int] NOT NULL CONSTRAINT [DF_CABINET_PAGETYPE] DEFAULT ((0)),
[ITEMSUBTYPENO] [int] NOT NULL CONSTRAINT [DF_CABINET_PAGENO] DEFAULT ((0)),
[PARENTID] [int] NOT NULL CONSTRAINT [DF_CABINET_PARENTID] DEFAULT ((0)),
[LASTUPDATED] [datetime] NULL,
[UPDATEDBY] [nvarchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CREATED] [datetime] NULL,
[CREATEDBY] [nvarchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACTIVE] [bit] NULL CONSTRAINT [DF_CABINET_ACTIVE] DEFAULT ((1)),
[LISTORDER] [int] NULL CONSTRAINT [DF_CABINET_LISTORDER] DEFAULT ((0)),
[CREATEDBYUSERID] [int] NULL CONSTRAINT [DF_CABINET_CREATEDBYUSERID] DEFAULT ((0)),
[UPDATEDBYUSERID] [int] NULL CONSTRAINT [DF_CABINET_UPDATEDBYUSERID] DEFAULT ((0)),
[PRIVACYID] [int] NULL CONSTRAINT [DF_CABINET_PRIVACYID] DEFAULT ((0)),
[PRIVACY] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsPrivate] [bit] NULL CONSTRAINT [DF_CABINET_IsPrivate] DEFAULT ((1))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CABINET] ADD CONSTRAINT [PK_CABINETID] PRIMARY KEY CLUSTERED  ([CABINETID]) ON [PRIMARY]
GO
