CREATE TABLE [dbo].[USERSPROFILES]
(
[PROFILEID] [int] NOT NULL IDENTITY(1, 1),
[USERID] [int] NULL,
[SUBSCRIPTIONID] [int] NULL,
[ACTIVE] [bit] NULL,
[DATESTART] [date] NULL,
[DATEND] [date] NULL,
[FILTER] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[INVISIBLE] [bit] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[USERSPROFILES] ADD CONSTRAINT [PK_USERPROFILES] PRIMARY KEY CLUSTERED  ([PROFILEID]) ON [PRIMARY]
GO
