CREATE TABLE [dbo].[CUSTOMERSXUSERS]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[CUSTOMERID] [int] NOT NULL CONSTRAINT [DF_CUSTOMERUSERS_CUSTOMERID] DEFAULT ((0)),
[USERID] [int] NOT NULL CONSTRAINT [DF_CUSTOMERUSERS_USERID] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CUSTOMERSXUSERS] ADD CONSTRAINT [PK_CUSTOMERUSERS] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
