CREATE TABLE [dbo].[LISTS]
(
[LISTID] [int] NOT NULL IDENTITY(1, 1),
[LASTUPDATED] [smalldatetime] NULL,
[UPDATEDBY] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CATEGORY] [nchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REFERENCE] [nchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LISTORDER] [int] NULL CONSTRAINT [DF_LISTS_Order] DEFAULT ((0)),
[CHECKED] [bit] NULL CONSTRAINT [DF_LISTS_CHECKED] DEFAULT ((0)),
[TIMELINE] [datetime] NULL,
[TITLE] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QUESTION] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ANSWER] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COMMENT] [ntext] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CASEID] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACTIONID] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ROWNO] [int] NULL CONSTRAINT [DF_LISTS_ROWNO] DEFAULT ((0)),
[SHEETNO] [int] NULL CONSTRAINT [DF_LISTS_SHEETNO] DEFAULT ((0)),
[CUSTOM1] [ntext] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CUSTOM2] [ntext] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CUSTOM3] [ntext] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DELFLAG] [bit] NULL CONSTRAINT [DF_LISTS_delflag] DEFAULT ((0)),
[TEMPLATEID] [int] NULL CONSTRAINT [DF_LISTS_TEMPLATEID] DEFAULT ((0))
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[LISTS] ADD CONSTRAINT [PK_LISTS] PRIMARY KEY CLUSTERED  ([LISTID]) ON [PRIMARY]
GO
