CREATE TABLE [dbo].[CUSTOMERS]
(
[CUSTOMERID] [int] NOT NULL IDENTITY(1, 1),
[PERSONID] [int] NULL,
[USERID] [int] NULL,
[REGNO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COMPANYCODE] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COMPANYNAME] [nvarchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADDRESSLINE1] [nchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADDRESSLINE2] [nchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CITY] [nchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POSTCODE] [nchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COUNTRY] [nchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TELEPHONE] [nchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMAIL] [nchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONTACTCARDTYPE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONTACTCARDNO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONTACTIDNO1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONTACTIDNO2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SUBSCRIPTIONID] [int] NULL,
[ACTIVE] [bit] NOT NULL CONSTRAINT [DF_CUSTOMERS_ACTIVE] DEFAULT ((1)),
[RATE1PERHOUR] [numeric] (18, 3) NULL,
[RATE2PERHOUR] [numeric] (18, 3) NULL,
[RATE3PERHOUR] [numeric] (18, 3) NULL,
[RATE4PERHOUR] [numeric] (18, 3) NULL,
[RATE1TEXT] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RATE2TEXT] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RATE3TEXT] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RATE4TEXT] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CUSTOMERS] ADD CONSTRAINT [PK_CUSTOMERS] PRIMARY KEY CLUSTERED  ([CUSTOMERID]) ON [PRIMARY]
GO
