CREATE TABLE [dbo].[REFERENCES]
(
[REFID] [int] NOT NULL IDENTITY(1, 1),
[REFERENCE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REFTYPE] [int] NULL,
[PERSON] [int] NULL,
[CASEID] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REFERENCES] ADD CONSTRAINT [PK_REFERENCES] PRIMARY KEY CLUSTERED  ([REFID]) ON [PRIMARY]
GO
