CREATE TABLE [dbo].[POIGALLERY]
(
[ID] [uniqueidentifier] NOT NULL ROWGUIDCOL,
[GALLERYID] [int] NOT NULL IDENTITY(1, 1),
[PERSONID] [int] NOT NULL CONSTRAINT [DF_POIGALLERY_PERSONID] DEFAULT ((0)),
[SUBSCRIPTIONID] [int] NULL CONSTRAINT [DF_POIGALLERY_SUBSCRIPTIONID] DEFAULT ((0)),
[CASEID] [int] NULL CONSTRAINT [DF_POIGALLERY_CASEID] DEFAULT ((0)),
[ACTIONID] [int] NULL CONSTRAINT [DF_POIGALLERY_ACTIONID] DEFAULT ((0)),
[PICTURE] [varbinary] (max) NULL,
[UPDATED] [datetime] NULL,
[UPDATEDBY] [int] NULL CONSTRAINT [DF_POIGALLERY_UPDATEDBY] DEFAULT ((0)),
[TITLE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DESCRIPTION] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATETAKEN] [datetime] NULL,
[PICTYPE] [int] NULL CONSTRAINT [DF_POIGALLERY_PICTYPE] DEFAULT ((0)),
[EXT] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[POIGALLERY] ADD CONSTRAINT [PK_POIGALLERY] PRIMARY KEY CLUSTERED  ([GALLERYID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[POIGALLERY] ADD CONSTRAINT [UQ__POIGALLE__3214EC2658042D84] UNIQUE NONCLUSTERED  ([ID]) ON [PRIMARY]
GO
