CREATE TABLE [dbo].[SUBRIGHTS]
(
[SUBRIGHTSID] [int] NOT NULL,
[SUBID] [int] NOT NULL,
[RIGHTCODE] [nchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RIGHTTITLE] [nchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RIGHTDESCRIPTION] [nchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RIGHTVALUE1] [numeric] (18, 0) NULL,
[RIGHTVALUE2] [numeric] (18, 0) NULL,
[ACTIVE] [bit] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SUBRIGHTS] ADD CONSTRAINT [PK_SUBRIGHTS] PRIMARY KEY CLUSTERED  ([SUBRIGHTSID]) ON [PRIMARY]
GO
