CREATE TABLE [dbo].[CASESTREEBASE]
(
[TREEID] [int] NOT NULL,
[CATEGORYID] [int] NULL,
[NODENAME] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NODEVALUE] [int] NULL,
[NODETEXT] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEFAULT] [bit] NULL,
[TREELEVEL] [int] NULL,
[TREELN] [int] NULL,
[TREERN] [int] NULL,
[ACTIVE] [bit] NULL,
[NODETAG] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PARENTID] [int] NOT NULL CONSTRAINT [DF_CASESTREEBASE_PARENTID] DEFAULT ((0)),
[NODEID] [int] NULL CONSTRAINT [DF_CASESTREEBASE_NODEID] DEFAULT ((0))
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[CASESTREEBASE] ADD CONSTRAINT [PK_CASESTREEBASE] PRIMARY KEY CLUSTERED  ([TREEID]) ON [PRIMARY]
GO
