CREATE TABLE [dbo].[REPORTS]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[DESCRIPTION] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NAME] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PARAMETERS] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACTIVE] [bit] NULL CONSTRAINT [DF_REPORTS_ACTIVE] DEFAULT ((1)),
[REPORTTYPE] [int] NULL,
[SUBSCRIPTIONID] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[REPORTS] ADD CONSTRAINT [PK_REPORTS] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
