CREATE TABLE [dbo].[REPORTSCHEDULEPARAMETERS]
(
[REPORTSCHEDULEPARAMETERID] [int] NOT NULL IDENTITY(1, 1),
[REPORTSCHEDULEID] [int] NULL,
[PARAMETERNAME] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PARAMETERVALUE] [nvarchar] (3000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
