CREATE TABLE [dbo].[POILOG]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[SUBID] [int] NULL,
[USERID] [int] NULL,
[LOGTYPE] [int] NULL,
[POID] [int] NULL,
[OLD] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NEW] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FIELD] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TIMESTAMP] [datetime] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[POILOG] ADD CONSTRAINT [PK_POILOG] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
