CREATE TABLE [dbo].[USERSPASSWORDS]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[USERID] [int] NOT NULL,
[PASSWORD] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SETDATE] [datetime] NOT NULL,
[ATTEMPTS] [int] NOT NULL CONSTRAINT [DF_USERSPASSWORDS_ATTEMPTS] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[USERSPASSWORDS] ADD CONSTRAINT [PK_USERSPASSWORDS] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
