CREATE TABLE [dbo].[CASESTREE]
(
[TREEID] [int] NOT NULL IDENTITY(1, 1),
[CATEGORYID] [int] NULL,
[NODENAME] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NODEVALUE] [int] NULL,
[NODETEXT] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEFAULT] [bit] NULL,
[TREELEVEL] [int] NULL CONSTRAINT [DF_CASESTREE_TREELEVEL] DEFAULT ((1)),
[TREELN] [int] NULL,
[TREERN] [int] NULL,
[ACTIVE] [bit] NULL,
[NODETAG] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PARENTID] [int] NULL CONSTRAINT [DF_CASESTREE_PARENTID] DEFAULT ((0)),
[NODEID] [int] NULL CONSTRAINT [DF_CASESTREE_NODEID] DEFAULT ((0)),
[RATE] [numeric] (18, 2) NULL CONSTRAINT [DF_CASESTREE_RATE] DEFAULT ((0))
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[CASESTREE] ADD CONSTRAINT [PK_CASETREE] PRIMARY KEY CLUSTERED  ([TREEID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [_dta_index_CASESTREE_8_211583892__K2] ON [dbo].[CASESTREE] ([CATEGORYID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [_dta_index_CASESTREE_7_211583892__K2_K10_K8_K9_K1_K3_4_5_6_7_11_12_13] ON [dbo].[CASESTREE] ([CATEGORYID], [ACTIVE], [TREELN], [TREERN], [TREEID], [NODENAME]) INCLUDE ([DEFAULT], [NODEID], [NODETAG], [NODETEXT], [NODEVALUE], [PARENTID], [TREELEVEL]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [NODETAGandCATEGORYID] ON [dbo].[CASESTREE] ([CATEGORYID], [NODETAG]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [_dta_index_CASESTREE_8_211583892__K2_K4_3] ON [dbo].[CASESTREE] ([CATEGORYID], [NODEVALUE]) INCLUDE ([NODENAME]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [_dta_index_CASESTREE_7_211583892__K2_K1_3] ON [dbo].[CASESTREE] ([CATEGORYID], [TREEID]) INCLUDE ([NODENAME]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [_dta_index_CASESTREE_7_211583892__K2_K1_5] ON [dbo].[CASESTREE] ([CATEGORYID], [TREEID]) INCLUDE ([NODETEXT]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [_dta_index_CASESTREE_7_211583892__K2_K1_K10_3_4_5_6_7_8_9_11_15] ON [dbo].[CASESTREE] ([CATEGORYID], [TREEID], [ACTIVE]) INCLUDE ([DEFAULT], [NODENAME], [NODETAG], [NODETEXT], [NODEVALUE], [RATE], [TREELEVEL], [TREELN], [TREERN]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [_dta_index_CASESTREE_8_211583892__K3_4] ON [dbo].[CASESTREE] ([NODENAME]) INCLUDE ([NODEVALUE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [_dta_index_CASESTREE_8_211583892__K4] ON [dbo].[CASESTREE] ([NODEVALUE]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [NODEVALUE] ON [dbo].[CASESTREE] ([NODEVALUE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [_dta_index_CASESTREE_8_1322487790__K4_3] ON [dbo].[CASESTREE] ([NODEVALUE]) INCLUDE ([NODENAME]) ON [PRIMARY]
GO
CREATE STATISTICS [_dta_stat_211583892_2_8_9_10_1_3] ON [dbo].[CASESTREE] ([CATEGORYID], [TREELN], [TREERN], [ACTIVE], [TREEID], [NODENAME])
GO
CREATE STATISTICS [_dta_stat_211583892_3_1_2_8_9] ON [dbo].[CASESTREE] ([NODENAME], [TREEID], [CATEGORYID], [TREELN], [TREERN])
GO
CREATE STATISTICS [_dta_stat_211583892_4_2] ON [dbo].[CASESTREE] ([NODEVALUE], [CATEGORYID])
GO
CREATE STATISTICS [_dta_stat_211583892_1_10] ON [dbo].[CASESTREE] ([TREEID], [ACTIVE])
GO
CREATE STATISTICS [_dta_stat_211583892_1_2_10_8] ON [dbo].[CASESTREE] ([TREEID], [CATEGORYID], [ACTIVE], [TREELN])
GO
CREATE STATISTICS [_dta_stat_211583892_1_2_8_9] ON [dbo].[CASESTREE] ([TREEID], [CATEGORYID], [TREELN], [TREERN])
GO
CREATE STATISTICS [_dta_stat_211583892_9_2_10] ON [dbo].[CASESTREE] ([TREERN], [CATEGORYID], [ACTIVE])
GO
