CREATE TABLE [dbo].[USERSRIGHTS]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[SUBSCRIPTIONID] [int] NULL,
[USERID] [int] NULL,
[CASEID] [int] NULL CONSTRAINT [DF_USERSRIGHTS_CASEID] DEFAULT ((0)),
[ACTIONID] [int] NULL CONSTRAINT [DF_USERSRIGHTS_ACTIONID] DEFAULT ((0)),
[NOINVITE] [bit] NULL CONSTRAINT [DF_USERSRIGHTS_NOINVITE] DEFAULT ((0)),
[NOCHANGE] [bit] NULL CONSTRAINT [DF_USERSRIGHTS_NOCHANGE] DEFAULT ((0)),
[NOASSIGN] [bit] NULL CONSTRAINT [DF_USERSRIGHTS_NOASSIGN] DEFAULT ((0)),
[NOASSIGNEE] [bit] NULL CONSTRAINT [DF_USERSRIGHTS_NOASSIGNEE] DEFAULT ((0)),
[INVISIBLE] [bit] NULL CONSTRAINT [DF_USERSRIGHTS_INVISIBLE] DEFAULT ((0)),
[NOUNINVITE] [bit] NULL,
[VIEWPRIVATE] [bit] NULL CONSTRAINT [DF_USERSRIGHTS_VIEWPRIVATE] DEFAULT ((0)),
[CHANGEPRIVATE] [bit] NULL CONSTRAINT [DF_USERSRIGHTS_CHANGEPRIVATE] DEFAULT ((0)),
[NOCASES] [bit] NULL CONSTRAINT [DF_USERSRIGHTS_APPLYTOCASES] DEFAULT ((0)),
[NOACTIONS] [bit] NULL CONSTRAINT [DF_USERSRIGHTS_APPLYTOACTIONS] DEFAULT ((0)),
[NOANALYSIS] [bit] NULL CONSTRAINT [DF_USERSRIGHTS_NOANALYSIS] DEFAULT ((0)),
[NOCUSTOMERS] [bit] NULL CONSTRAINT [DF_USERSRIGHTS_NOCUSTOMERS] DEFAULT ((0)),
[NOSCHEDULES] [bit] NULL CONSTRAINT [DF_USERSRIGHTS_NOSCHEDULES] DEFAULT ((0)),
[NOMAINTENANCE] [bit] NULL CONSTRAINT [DF_USERSRIGHTS_NOMAINTENANCE] DEFAULT ((0)),
[NOMONITORING] [bit] NULL CONSTRAINT [DF_USERSRIGHTS_NOMONITORING] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[USERSRIGHTS] ADD CONSTRAINT [PK_USERSRIGHTS] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
