CREATE TABLE [dbo].[RULES]
(
[RULESID] [int] NOT NULL IDENTITY(1, 1),
[TITLE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DESCRIPTION] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[APPLIESTO] [nchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[APPLIESTOTYPE] [int] NULL CONSTRAINT [DF_RULES_APPLIESTOTYPE] DEFAULT ((0)),
[VALUE] [nchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FILTER] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RULETYPE] [int] NOT NULL CONSTRAINT [DF_RULES_RULETYPE] DEFAULT ((0)),
[LOGICTYPE] [int] NULL,
[CREATEDBY] [int] NOT NULL,
[CREATED] [datetime] NULL,
[UPDATEDBY] [int] NULL,
[UPDATED] [datetime] NULL,
[SUBSCRIPTIONID] [int] NULL CONSTRAINT [DF_RULES_SUBSCRIPTIONID] DEFAULT ((0)),
[ACTIVE] [bit] NULL CONSTRAINT [DF_RULES_ACTIVE] DEFAULT ((1)),
[CASEID] [int] NULL CONSTRAINT [DF_RULES_CASEID] DEFAULT ((0)),
[RULENO] [int] NULL CONSTRAINT [DF_RULES_RULENO] DEFAULT ((0)),
[STEPNO] [int] NULL CONSTRAINT [DF_RULES_STEPNO] DEFAULT ((0)),
[TRIGGERFIELD] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[RULES] ADD CONSTRAINT [PK_RULES] PRIMARY KEY CLUSTERED  ([RULESID]) ON [PRIMARY]
GO
