CREATE TABLE [dbo].[CASESXTREES]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[CASEID] [int] NULL,
[ACTIONID] [int] NULL,
[TREEID] [int] NULL,
[CATEGORYID] [int] NULL CONSTRAINT [DF_CASESXTREES_CATEGORYID] DEFAULT ((0)),
[NODEVALUE] [int] NULL CONSTRAINT [DF_CASESXTREES_NODEVALUE] DEFAULT ((0)),
[NODENUMBER] [numeric] (18, 2) NULL CONSTRAINT [DF_CASESXTREES_NODENUMBER] DEFAULT ((0.00)),
[NODENAME] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[CASESXTREES] ADD CONSTRAINT [PK_CASESXTREES] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [PK1_CASEID] ON [dbo].[CASESXTREES] ([CASEID], [TREEID], [CATEGORYID]) ON [PRIMARY]
GO
