CREATE TABLE [dbo].[NOTES]
(
[NOTESID] [int] NOT NULL IDENTITY(1, 1),
[TITLE] [nvarchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NOTESHTM] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VERSION] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_NOTES_VERSION] DEFAULT ('1.0'),
[LASTUPDATED] [datetime] NULL,
[UPDATEDBY] [int] NULL,
[PAGENO] [int] NULL CONSTRAINT [DF_NOTES_PAGENO] DEFAULT ((1)),
[CASEID] [int] NULL,
[ACTIONID] [int] NULL,
[NOTETYPE] [int] NULL CONSTRAINT [DF_NOTES_NOTETYPE] DEFAULT ((0)),
[CREATEDBY] [int] NULL,
[CREATEDDATE] [datetime] NULL,
[PERSONID] [int] NULL CONSTRAINT [DF_NOTES_PERSONID] DEFAULT ((0)),
[LISTID] [int] NULL,
[ACTIVE] [bit] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[NOTES] ADD CONSTRAINT [PK_NOTES] PRIMARY KEY CLUSTERED  ([NOTESID]) ON [PRIMARY]
GO
