CREATE TABLE [dbo].[SCH_INVITEES]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[USERID] [int] NULL,
[EVENTID] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SCH_INVITEES] ADD CONSTRAINT [PK_SCH_INVITEES] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
