CREATE TABLE [dbo].[REPORTSCHEDULELOGS]
(
[REPORTSCHEDULELOGID] [int] NOT NULL IDENTITY(1, 1),
[REPORTSCHEDULEID] [int] NULL,
[LOGTIME] [datetime] NULL,
[LOG] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
