CREATE TABLE [dbo].[PDFFORMS]
(
[FORMID] [int] NOT NULL IDENTITY(1, 1),
[CASEID] [int] NOT NULL CONSTRAINT [DF_PDFFORMS_CASEID] DEFAULT ((0)),
[ACTIONID] [int] NOT NULL CONSTRAINT [DF_PDFFORMS_ACTIONID] DEFAULT ((0)),
[ATTACHMENTID] [int] NOT NULL CONSTRAINT [DF_Table_1_CABINETID] DEFAULT ((0)),
[CABINETID] [int] NOT NULL CONSTRAINT [DF_PDFFORMS_CABINETID] DEFAULT ((0)),
[FDF] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PDFFIELDS] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_PDFFORMS_PDFFIELDS] DEFAULT ('     '),
[LASTUPDATED] [datetime] NOT NULL,
[UPDATEDBYUSERID] [int] NOT NULL CONSTRAINT [DF_PDFFORMS_UPDATEDBYID] DEFAULT ((0)),
[UPDATEDBY] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DATECREATED] [datetime] NOT NULL,
[CREATEDBYUSERID] [int] NOT NULL CONSTRAINT [DF_PDFFORMS_CREATEDBYUSERID] DEFAULT ((0)),
[CREATEDBY] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ACTIVE] [bit] NOT NULL CONSTRAINT [DF_PDFFORMS_ACTIVE] DEFAULT ((1)),
[TYPENO] [int] NULL CONSTRAINT [DF_PDFFORMS_TYPENO] DEFAULT ((1)),
[SEQNO] [int] NULL CONSTRAINT [DF_PDFFORMS_SEQNO] DEFAULT ((1)),
[REVNO] [int] NULL CONSTRAINT [DF_PDFFORMS_REVNO] DEFAULT ((1))
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[PDFFORMS] ADD CONSTRAINT [PK_PDFFORMS] PRIMARY KEY CLUSTERED  ([FORMID]) ON [PRIMARY]
GO
