CREATE TABLE [dbo].[CUSTOMERSXFACILITIES]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[CUSTOMERID] [int] NULL,
[TREEID] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CUSTOMERSXFACILITIES] ADD CONSTRAINT [PK_CUSTOMERSXFACILITIES] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
