CREATE TABLE [dbo].[TEMPLATESBASE]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[TEMPLATEID] [int] NOT NULL,
[TEMPLATENAME] [nchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COMMENT] [nchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TEMPLATESBASE] ADD CONSTRAINT [PK_TEMPLATESBASE] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
