CREATE TABLE [dbo].[CATEGORIESBASE]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[CATEGORYID] [int] NOT NULL,
[TEMPLATEID] [int] NULL,
[CATNAME] [nchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CATDESC] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CATOF] [nchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CATOFFIELDNAME] [nchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ATTNO] [int] NULL,
[ATTNAME1] [nchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ATTNAME2] [nchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ATTNAME3] [nchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ATTNAME4] [nchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ATTNAME5] [nchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACTIVE] [bit] NOT NULL,
[ATTRELNO] [int] NULL,
[ATTRELID] [int] NULL,
[RENDERTOLEVEL] [int] NULL,
[LEAFATLEVEL] [int] NULL,
[LANGUAGE] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TERMS] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[CATEGORIESBASE] ADD CONSTRAINT [PK_CATEGORIESBASE_1] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
