SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO



CREATE FUNCTION [dbo].[cmsListTreePathsByID]
(
	@TREEID	integer,@CATEGORYID integer
)
RETURNS @PATHS TABLE (TREELEVEL INT IDENTITY(1,1), NODENAME varchar(250), NODEVALUE integer,TREEID  integer,PARENTID integer)
BEGIN
	INSERT INTO @PATHS

	SELECT PARENT.NODENAME,PARENT.NODEVALUE,PARENT.TREEID,PARENT.PARENTID
	FROM CASESTREE AS NODE,CASESTREE AS PARENT
	WHERE node.TREELN BETWEEN parent.TREELN AND parent.TREERN AND parent.CATEGORYID=@CATEGORYID
	AND NODE.TREEID=@TREEID ORDER BY PARENT.TREELN  
	RETURN
END


GO
