SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE FUNCTION dbo.stp_GetGUID
(
	@GALLERYID	integer
)
RETURNS @PATHS TABLE (ID  UNIQUEIDENTIFIER)
BEGIN
	INSERT INTO @PATHS

	SELECT ID FROM POIGALLERY WHERE GALLERYID=@GALLERYID  
	RETURN
END
GO
