SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[rptTSGroupByCase]
AS
SELECT     CASEID, SUM(PENALTIES) AS Penalties, SUM(TOTALVALUE + RECOVEREDVALUE) AS Losses, SUM(RECOVEREDVALUE) AS Recovery, USERID
FROM         dbo.rptTSActivityCases
GROUP BY CASEID, USERID

GO
