SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO



CREATE VIEW [dbo].[ORGANIZATIONS_TS]
AS
SELECT     SUBSTRING(dbo.SUBSCRIPTIONS.TMROLE, 1, CHARINDEX('.', dbo.SUBSCRIPTIONS.TMROLE) - 1) AS COMPANY, RIGHT(dbo.SUBSCRIPTIONS.TMSUBNAME, 2) 
                      AS COUNTRYCODE, dbo.COUNTRIES.COUNTRY_NAME, dbo.SUBSCRIPTIONS.TMROLE, dbo.CASESTREE.NODENAME, dbo.CASESTREE.NODEVALUE, 
                      dbo.CASESTREE.NODETEXT, dbo.CASESTREE.TREELN, dbo.CASESTREE.TREERN, dbo.CASESTREE.NODETAG, dbo.SUBSCRIPTIONS.SUBSCRIPTIONID, 
                      dbo.CASESTREE.NODEID, dbo.CASESTREE.PARENTID, dbo.SUBSCRIPTIONS.SITECODE, dbo.SUBSCRIPTIONS.FLAG1, dbo.SUBSCRIPTIONS.FLAG2, 
                      dbo.SUBSCRIPTIONS.FLAG3, dbo.SUBSCRIPTIONSEXT.FLAG4, dbo.SUBSCRIPTIONSEXT.FLAG5, dbo.SUBSCRIPTIONSEXT.FLAG6, dbo.SUBSCRIPTIONS.ACTIVE
FROM         dbo.SUBSCRIPTIONS LEFT OUTER JOIN
                      dbo.COUNTRIES ON RIGHT(dbo.SUBSCRIPTIONS.TMROLE, 2) = LEFT(dbo.COUNTRIES.COUNTRYCODE, 2) LEFT OUTER JOIN
                      dbo.CASESTREE ON dbo.SUBSCRIPTIONS.SUBSCRIPTIONID = dbo.CASESTREE.NODEVALUE LEFT OUTER JOIN
                      dbo.SUBSCRIPTIONSEXT ON dbo.SUBSCRIPTIONS.SUBSCRIPTIONID = dbo.SUBSCRIPTIONSEXT.SUBSCRIPTIONID
WHERE     (dbo.SUBSCRIPTIONS.TMROLE <> 'Help') AND (dbo.SUBSCRIPTIONS.SUBSCRIPTIONID <> 0)

GO
