SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[LOCALIZATIONSOLD]
AS
SELECT dbo.TMLOCALIZATIONS.ID, INVTMLOCALIZATIONS.BASEKEY, INVTMLOCALIZATIONS.LOCAL AS ENGLISH, dbo.TMLOCALIZATIONS.CODE, dbo.TMLOCALIZATIONS.LOCAL, 
               dbo.TMLOCALIZATIONS.UPDATED, dbo.TMLOCALIZATIONS.CREATED, dbo.TMLOCALIZATIONS.UPDATEDBY, INVTMLOCALIZATIONS.ACTIVE, INVTMLOCALIZATIONS.LOCKED
FROM  dbo.TMLOCALIZATIONS INNER JOIN
               dbo.TMLOCALIZATIONS AS INVTMLOCALIZATIONS ON dbo.TMLOCALIZATIONS.BASEKEY = INVTMLOCALIZATIONS.BASEKEY
WHERE (INVTMLOCALIZATIONS.CODE = N'-') AND (dbo.TMLOCALIZATIONS.CODE <> N'-') AND (LEFT(INVTMLOCALIZATIONS.BASEKEY, 1) = 'S' OR
               LEFT(INVTMLOCALIZATIONS.BASEKEY, 1) = 'C')

GO
