SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE VIEW [dbo].[AllCASESTree]
AS
SELECT DISTINCT 
                      dbo.SUBSXTEMPLATES.TEMPLATEID, dbo.SUBSXTEMPLATES.SUBSCRIPTIONID, dbo.CATEGORIES.CATNAME, dbo.CASESTREE.NODENAME, 
                      dbo.CASESTREE.TREEID, dbo.CASESTREE.CATEGORYID, dbo.CASESTREE.[DEFAULT], dbo.CASESTREE.TREELN, dbo.CASESTREE.TREERN, 
                      dbo.CATEGORIES.CATOFFIELDNAME, dbo.CASESTREE.NODEVALUE, dbo.CASESTREE.NODETEXT, dbo.CASESTREE.ACTIVE, dbo.CASESTREE.TREELEVEL, 
                      dbo.CATEGORIES.RENDERTOLEVEL, dbo.CASESTREE.NODETAG, dbo.CATEGORIES.LANGUAGE, dbo.CATEGORIES.TERMS, dbo.CATEGORIES.ISGLOBAL, 
                      dbo.CATEGORIES.ISADMIN, dbo.CASESTREE.RATE
FROM         dbo.CATEGORIES INNER JOIN
                      dbo.CASESTREE ON dbo.CATEGORIES.CATEGORYID = dbo.CASESTREE.CATEGORYID INNER JOIN
                      dbo.SUBSXTEMPLATES ON dbo.CATEGORIES.TEMPLATEID = dbo.SUBSXTEMPLATES.TEMPLATEID


GO
