SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[ALLPEOPLE]
AS
SELECT     dbo.SUBSCRIPTIONS.DESCRIPTION AS Expr2, dbo.SUBSCRIPTIONS.TMROLE, dbo.CASES.SUBSCRIPTIONID AS Expr3, dbo.CASES.REFERENCE, 
                      dbo.CASES.TITLE AS Expr4, dbo.CASES.EVENTDESCRIPTION, dbo.PERSONS.LASTNAME AS Expr8, dbo.PERSONS.PERSONADDRESS1 AS Expr9, 
                      dbo.PERSONS.PERSONADDRESS2 AS Expr10, dbo.PERSONS.ACTIVE AS Expr15, dbo.PERSONS.BIRTHDATE AS Expr17, 
                      dbo.PERSONS.BIRTHPLACE AS Expr18, dbo.PERSONS.PERSONID, dbo.PERSONS.ACTIONID, dbo.PERSONS.CASEID, dbo.PERSONS.UPDATED, 
                      dbo.PERSONS.UPDATEDBY, dbo.PERSONS.TITLE, dbo.PERSONS.FIRSTNAME, dbo.PERSONS.MIDDLENAME, dbo.PERSONS.LASTNAME, 
                      dbo.PERSONS.PERSONADDRESS1, dbo.PERSONS.PERSONADDRESS2, dbo.PERSONS.PERSONADDRESS3, dbo.PERSONS.CITY, 
                      dbo.PERSONS.POSTCODE, dbo.PERSONS.COUNTRY, dbo.PERSONS.PERSONREF1, dbo.PERSONS.PERSONREFTYPE1, dbo.PERSONS.PERSONREF2, 
                      dbo.PERSONS.PERSONREFTYPE2, dbo.PERSONS.PERSONREF3, dbo.PERSONS.PERSONREFTYPE3, dbo.PERSONS.PERSONREF4, 
                      dbo.PERSONS.PERSONREFTYPE4, dbo.PERSONS.SUBSCRIPTIONID, dbo.PERSONS.REL1, dbo.PERSONS.RELTYPE1, dbo.PERSONS.REL2, 
                      dbo.PERSONS.RELTYPE2, dbo.PERSONS.REL3, dbo.PERSONS.RELTYPE3, dbo.PERSONS.CONTACTNO1, dbo.PERSONS.CONTACTNO2, 
                      dbo.PERSONS.CONTACTNO3, dbo.PERSONS.CONTACTNO4, dbo.PERSONS.NOTE, dbo.PERSONS.ACTIVE, dbo.PERSONS.CARDNO, 
                      dbo.PERSONS.CARDCOUNTRY, dbo.PERSONS.CARDNAME, dbo.PERSONS.CARDLEVEL, dbo.PERSONS.BIRTHDATE, dbo.PERSONS.BIRTHPLACE, 
                      dbo.PERSONS.COMPANY, dbo.PERSONS.COMPANYSINCE, dbo.PERSONS.DESCRIPTION, dbo.PERSONS.VEHICLEINVOLVED, 
                      dbo.PERSONS.VEHICLEBRAND, dbo.PERSONS.VEHICLEPLATE, dbo.PERSONS.VEHICLETYPE, dbo.PERSONS.ISCHILD, dbo.PERSONS.ISEMPLOYEE, 
                      dbo.PERSONS.ISSUSPECT, dbo.PERSONS.ISGUILTY, dbo.PERSONS.ISPENALTYPAID, dbo.PERSONS.ISPENALTYDEMANDED, 
                      dbo.PERSONS.PENALTYAMOUNT, dbo.PERSONS.GENDERID, dbo.PERSONS.TITLEID, dbo.PERSONS.CARDTYPE1, dbo.PERSONS.CARDTYPE2, 
                      dbo.PERSONS.CARDTYPE3, dbo.PERSONS.CARDBLOCKED, dbo.PERSONS.ISKNOWN, dbo.PERSONS.REL, dbo.PERSONS.RELTYPE, 
                      dbo.PERSONS.KINFIRSTNAME, dbo.PERSONS.KINLASTNAME, dbo.PERSONS.AGE, dbo.PERSONS.ISFLAG1, dbo.PERSONS.ISFLAG2, 
                      dbo.PERSONS.ISFLAG3, dbo.PERSONS.ISFLAG4, dbo.PERSONS.ISFLAG5, dbo.PERSONS.ISFLAG6, dbo.PERSONS.DESCRIPTION1, 
                      dbo.PERSONS.DESCRIPTION2, dbo.PERSONS.DESCRIPTION3, dbo.PERSONS.DESCRIPTION4, dbo.PERSONS.DESCRIPTION5, 
                      dbo.PERSONS.DESCRIPTION6, dbo.PERSONS.NEXTOFKIN, CASESTREE_1.NODENAME AS CARDTYPE, CASESTREE_2.NODENAME AS NATIONALITY, 
                      CASESTREE_3.NODENAME AS BIRTHCOUNTRY, dbo.CASESTREE.NODENAME AS GENDER
FROM         dbo.SUBSCRIPTIONS INNER JOIN
                      dbo.CASES ON dbo.SUBSCRIPTIONS.SUBSCRIPTIONID = dbo.CASES.SUBSCRIPTIONID INNER JOIN
                      dbo.PERSONS ON dbo.CASES.CASEID = dbo.PERSONS.CASEID LEFT OUTER JOIN
                      dbo.CASESTREE ON dbo.PERSONS.GENDERID = dbo.CASESTREE.NODEVALUE LEFT OUTER JOIN
                      dbo.CASESTREE AS CASESTREE_3 ON dbo.PERSONS.NATIONALITY = CASESTREE_3.NODEVALUE LEFT OUTER JOIN
                      dbo.CASESTREE AS CASESTREE_2 ON dbo.PERSONS.BIRTHCOUNTRY = CASESTREE_2.NODEVALUE LEFT OUTER JOIN
                      dbo.CASESTREE AS CASESTREE_1 ON dbo.PERSONS.CARDTYPE1 = CASESTREE_1.NODEVALUE

GO
