SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[ALLSUBSCRIPTIONS]
AS
SELECT     dbo.SUBSCRIPTIONS.*, dbo.SUBSCRIPTIONSEXT.FLAG4, dbo.SUBSCRIPTIONSEXT.FLAG5, dbo.SUBSCRIPTIONSEXT.FLAG6
FROM         dbo.SUBSCRIPTIONS INNER JOIN
                      dbo.SUBSCRIPTIONSEXT ON dbo.SUBSCRIPTIONS.SUBSCRIPTIONID = dbo.SUBSCRIPTIONSEXT.SUBSCRIPTIONID


GO
