SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE VIEW [dbo].[ALLCUSTOMERUSERS]
AS
SELECT     dbo.CUSTOMERS.CUSTOMERID, dbo.CUSTOMERS.COMPANYNAME, dbo.CUSTOMERS.COMPANYCODE, dbo.CUSTOMERS.ADDRESSLINE1, 
                      dbo.CUSTOMERS.ADDRESSLINE2, dbo.CUSTOMERS.CITY, dbo.CUSTOMERS.POSTCODE, dbo.CUSTOMERS.COUNTRY, dbo.CUSTOMERS.TELEPHONE, 
                      dbo.CUSTOMERS.EMAIL AS COMPANYEMAIL, dbo.CUSTOMERS.REGNO, dbo.ALLUSERS.FirstName, dbo.ALLUSERS.LastName, dbo.ALLUSERS.IsDetective, 
                      dbo.ALLUSERS.Email, dbo.ALLUSERS.Admin, dbo.ALLUSERS.ManagerName, dbo.ALLUSERS.ManagerEmail, dbo.ALLUSERS.AgencyID, 
                      dbo.CUSTOMERS.ACTIVE AS ACTIVECUSTOMER, dbo.ALLUSERS.Active AS ACTIVEUSER, dbo.ALLUSERS.CodeOrganization, dbo.ALLUSERS.UserId
FROM         dbo.CUSTOMERS INNER JOIN
                      dbo.CUSTOMERSXUSERS ON dbo.CUSTOMERS.CUSTOMERID = dbo.CUSTOMERSXUSERS.CUSTOMERID INNER JOIN
                      dbo.ALLUSERS ON dbo.CUSTOMERSXUSERS.USERID = dbo.ALLUSERS.UserId


GO
