SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[ALLLOCATIONS]
AS
SELECT     dbo.ALLCASESTREETERMS.CATEGORYID, dbo.USERS.DNNNAME, dbo.USERS.UserId, dbo.ALLCASESTREETERMS.NODENAME, 
                      dbo.ALLCASESTREETERMS.NODETEXT, dbo.ALLCASESTREETERMS.ACTIVE, dbo.ALLCASESTREETERMS.UPDATEDBY, 
                      dbo.ALLCASESTREETERMS.LASTUPDATED, dbo.ALLCASESTREETERMS.TEXT1, dbo.ALLCASESTREETERMS.TEXT2, 
                      dbo.ALLCASESTREETERMS.TREELN, dbo.ALLCASESTREETERMS.TREERN, dbo.ALLCASESTREETERMS.PARENTID, 
                      dbo.ALLCASESTREETERMS.NODETAG, dbo.USERS.UserName, dbo.USERS.LastName
FROM         dbo.ALLCASESTREETERMS INNER JOIN
                      dbo.USERS ON dbo.ALLCASESTREETERMS.NODEID = dbo.USERS.UserId
WHERE     (dbo.ALLCASESTREETERMS.CATEGORYID = 1302)

GO
