SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO



CREATE VIEW [dbo].[rptPERSONCASES]
AS
SELECT     PERSONID, ACTIONID, CASEID, UPDATED, UPDATEDBY, TITLE, FIRSTNAME, MIDDLENAME, LASTNAME, PERSONADDRESS1, PERSONADDRESS2, 
                      PERSONADDRESS3, CITY, POSTCODE, COUNTRY, CONTACTNO1, CONTACTNO2, CONTACTNO3, CONTACTNO4, NOTE, ACTIVE, CARDNO, CARDCOUNTRY, 
                      CARDNAME, CARDLEVEL, GENDER, BIRTHDATE, BIRTHPLACE, BIRTHCOUNTRY, NATIONALITY, COMPANY, COMPANYSINCE, DESCRIPTION, VEHICLEINVOLVED, 
                      VEHICLEBRAND, VEHICLEPLATE, VEHICLETYPE, ISCHILD, ISEMPLOYEE, ISSUSPECT, ISGUILTY, ISPENALTYPAID, ISPENALTYDEMANDED, PENALTYAMOUNT, 
                      ISKNOWN, AGE, DESCRIPTION1, DESCRIPTION2, DESCRIPTION3, DESCRIPTION4, DESCRIPTION5, DESCRIPTION6, NEXTOFKIN, IDCARDNO, REFERENCE, 
                      LOCATION, DAYS, RIGHT(BIRTHDATE, 4) AS BIRTHYEAR
FROM         dbo.PERSONSCASES

GO
