SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE VIEW [dbo].[ALLCUSTOMERFACILITIESUNALLOCATED]
AS
SELECT     TOP (100) PERCENT dbo.CASESTREE.NODENAME, dbo.CASESTREE.CATEGORYID, dbo.CASESTREE.TREEID, dbo.CASESTREE.NODETEXT, 
                      dbo.CASESTREE.NODEVALUE, dbo.CUSTOMERSXFACILITIES.CUSTOMERID
FROM         dbo.CASESTREE LEFT OUTER JOIN
                      dbo.CUSTOMERSXFACILITIES ON dbo.CASESTREE.TREEID = dbo.CUSTOMERSXFACILITIES.TREEID
WHERE     (dbo.CASESTREE.CATEGORYID = 1302) AND (dbo.CASESTREE.NODETEXT = N'REAL.DE') AND (dbo.CASESTREE.TREELEVEL > 3) AND 
                      (dbo.CUSTOMERSXFACILITIES.CUSTOMERID IS NULL)
ORDER BY dbo.CASESTREE.NODENAME


GO
