SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[SUBSCRIPTIONCODES]
AS
SELECT     ID, SUBSCRIPTIONID, TMROLE, TMSUBNAME, ACTIVE, DESCRIPTION, THEMEID, HOMEURL, SITECODE, CREATED, SITEID, SUBTYPE, ALIASES, FLAG1, FLAG2, 
                      FLAG3, PARSENAME(TMROLE, 1) AS COUNTRY_CODE, PARSENAME(TMROLE, 2) AS COMPANY
FROM         dbo.SUBSCRIPTIONS


GO
