SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE dbo.stp_AddBLOB
AS
BEGIN
  DECLARE @ID UNIQUEIDENTIFIER
  SET @ID = NEWID()
  INSERT INTO dbo.POIGALLERY
    (ID, PICTURE)
  VALUES 
    (@ID, CAST('' AS VARBINARY(MAX)))
  SELECT ID,PICTURE.PathName(),GALLERYID
  FROM dbo.POIGALLERY
  WHERE ID = @ID
END
	RETURN
GO
