SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Gets all records from the 'ORGANIZATIONS_TS' table.
CREATE PROCEDURE [dbo].[_ORGANIZATIONS_TS_GetAll]
AS
	SELECT * FROM [dbo].[ORGANIZATIONS_TS]
GO
