SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Deletes all records from the 'REPORTSCHEDULEPARAMETERS' table.
CREATE PROCEDURE [dbo].[_REPORTSCHEDULEPARAMETERS_DeleteAll]
AS
	DELETE FROM [dbo].[REPORTSCHEDULEPARAMETERS]
GO
