SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

-- Inserts a new record into the 'CUSTOMERSXFACILITYUSER' table.
CREATE PROCEDURE [dbo].[_CUSTOMERSXFACILITYUSER_Insert]
	@TREEID int,
	@CUSTOMERID int,
	@USERID int
AS
	INSERT INTO [dbo].[CUSTOMERSXFACILITYUSER]
	(
		[TREEID],
		[CUSTOMERID],
		[USERID]
	)
	VALUES
	(
		@TREEID,
		@CUSTOMERID,
		@USERID
	)
	SELECT @@IDENTITY
GO
