SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Gets all records from the 'ALLCASESTREETERMS' table.
CREATE PROCEDURE [dbo].[_ALLCASESTREETERMS_GetAll]
AS
	SELECT * FROM [dbo].[ALLCASESTREETERMS]
GO
