SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE dbo.cmsGetCaseQueryClassification @SubscriptionID INTEGER=0
AS
SET NOCOUNT ON
	SELECT NODENAME,
	       NODEVALUE
	FROM [TM].[dbo].[CASESTREE]
	WHERE [CATEGORYID] = 1501 -- Classification
	AND TREELEVEL = 2

GO
