SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Gets all records from the 'rptSUMMARYFINANCIAL' table.
CREATE PROCEDURE [dbo].[_rptSUMMARYFINANCIAL_GetAll]
AS
	SELECT * FROM [dbo].[rptSUMMARYFINANCIAL]
GO
