SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Deletes all records from the 'TMLOCALIZATIONSCOPY' table.
CREATE PROCEDURE [dbo].[_TMLOCALIZATIONSCOPY_DeleteAll]
AS
	DELETE FROM [dbo].[TMLOCALIZATIONSCOPY]
GO
