SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Gets all records from the 'ALLCUSTOMERFACILITIESUNALLOCATED' table.
CREATE PROCEDURE [dbo].[_ALLCUSTOMERFACILITIESUNALLOCATED_GetAll]
AS
	SELECT * FROM [dbo].[ALLCUSTOMERFACILITIESUNALLOCATED]
GO
