SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Inserts a new record into the 'REPORTSCHEDULEEMAILS' table.
CREATE PROCEDURE [dbo].[_REPORTSCHEDULEEMAILS_Insert]
	@REPORTSCHEDULEID int,
	@EMAIL nvarchar(500)
AS
	INSERT INTO [dbo].[REPORTSCHEDULEEMAILS]
	(
		[REPORTSCHEDULEID],
		[EMAIL]
	)
	VALUES
	(
		@REPORTSCHEDULEID,
		@EMAIL
	)
	SELECT @@IDENTITY
GO
