SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

-- Deletes all records from the 'LEDGERVALUES_1712' table.
CREATE PROCEDURE [dbo].[_LEDGERVALUES_1712_DeleteAll]
AS
	DELETE FROM [dbo].[LEDGERVALUES_1712]
GO
