SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Deletes all records from the 'SUBSCRIPTIONSEXT' table.
CREATE PROCEDURE [dbo].[_SUBSCRIPTIONSEXT_DeleteAll]
AS
	DELETE FROM [dbo].[SUBSCRIPTIONSEXT]
GO
