SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Inserts a new record into the 'TEMPLATESBASE' table.
CREATE PROCEDURE [dbo].[_TEMPLATESBASE_Insert]
	@TEMPLATEID int,
	@TEMPLATENAME nchar(50),
	@COMMENT nchar(50)
AS
	INSERT INTO [dbo].[TEMPLATESBASE]
	(
		[TEMPLATEID],
		[TEMPLATENAME],
		[COMMENT]
	)
	VALUES
	(
		@TEMPLATEID,
		@TEMPLATENAME,
		@COMMENT
	)
	SELECT @@IDENTITY
GO
