SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Inserts a new record into the 'RELATIONSHIPS' table.
CREATE PROCEDURE [dbo].[_RELATIONSHIPS_Insert]
	@CATEGORYID int,
	@RELNAME nchar(20),
	@RELDESC nvarchar(max),
	@DISPLAYNAME nchar(50)
AS
	INSERT INTO [dbo].[RELATIONSHIPS]
	(
		[CATEGORYID],
		[RELNAME],
		[RELDESC],
		[DISPLAYNAME]
	)
	VALUES
	(
		@CATEGORYID,
		@RELNAME,
		@RELDESC,
		@DISPLAYNAME
	)
	SELECT @@IDENTITY
GO
