SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Gets all records from the 'ALLCUSTOMERUSERSUNALLOCATED' table.
CREATE PROCEDURE [dbo].[_ALLCUSTOMERUSERSUNALLOCATED_GetAll]
AS
	SELECT * FROM [dbo].[ALLCUSTOMERUSERSUNALLOCATED]
GO
