SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

-- Gets a record from the 'CUSTOMERSXFACILITYUSER' table using the primary key value.
CREATE PROCEDURE [dbo].[_CUSTOMERSXFACILITYUSER_GetByPrimaryKey]
	@ID int
AS
	SELECT * FROM [dbo].[CUSTOMERSXFACILITYUSER] WHERE
		[ID] = @ID
GO
