SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Deletes all records from the 'REPORTSCHEDULEEMAILS' table.
CREATE PROCEDURE [dbo].[_REPORTSCHEDULEEMAILS_DeleteAll]
AS
	DELETE FROM [dbo].[REPORTSCHEDULEEMAILS]
GO
