SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE dbo.cmsGetCaseQueryLocation @SubscriptionID INTEGER=0, @Role VARCHAR(100)=''
AS
SET NOCOUNT ON

	SELECT NODENAME,
	       NODEVALUE,
	       NODETEXT,
	       TREELEVEL
	FROM CASESTREE WHERE CATEGORYID = 1302 -- Location
	AND ACTIVE = 1
	AND (@Role = '' OR @Role = NODETEXT)
	AND TREELEVEL > 1
	ORDER BY NODETEXT,
	         TREELEVEL,
	         NODENAME

GO
