SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Updates a record in the 'CUSTOMERS' table.
CREATE PROCEDURE [dbo].[_CUSTOMERS_Update]
	-- The rest of writeable parameters
	@PERSONID int,
	@USERID int,
	@REGNO nvarchar(50),
	@COMPANYCODE nchar(10),
	@COMPANYNAME nvarchar(70),
	@ADDRESSLINE1 nchar(70),
	@ADDRESSLINE2 nchar(70),
	@CITY nchar(70),
	@POSTCODE nchar(20),
	@COUNTRY nchar(70),
	@TELEPHONE nchar(30),
	@EMAIL nchar(30),
	@CONTACTCARDTYPE nvarchar(50),
	@CONTACTCARDNO nvarchar(50),
	@CONTACTIDNO1 nvarchar(50),
	@CONTACTIDNO2 nvarchar(50),
	@SUBSCRIPTIONID int,
	@ACTIVE bit,
	@RATE1PERHOUR numeric(18,3),
	@RATE2PERHOUR numeric(18,3),
	@RATE3PERHOUR numeric(18,3),
	@RATE4PERHOUR numeric(18,3),
	@RATE1TEXT nvarchar(50),
	@RATE2TEXT nvarchar(50),
	@RATE3TEXT nvarchar(50),
	@RATE4TEXT nvarchar(50),
	-- Primary key parameters
	@CUSTOMERID int
AS
	UPDATE [dbo].[CUSTOMERS] SET
		[PERSONID] = @PERSONID,
		[USERID] = @USERID,
		[REGNO] = @REGNO,
		[COMPANYCODE] = @COMPANYCODE,
		[COMPANYNAME] = @COMPANYNAME,
		[ADDRESSLINE1] = @ADDRESSLINE1,
		[ADDRESSLINE2] = @ADDRESSLINE2,
		[CITY] = @CITY,
		[POSTCODE] = @POSTCODE,
		[COUNTRY] = @COUNTRY,
		[TELEPHONE] = @TELEPHONE,
		[EMAIL] = @EMAIL,
		[CONTACTCARDTYPE] = @CONTACTCARDTYPE,
		[CONTACTCARDNO] = @CONTACTCARDNO,
		[CONTACTIDNO1] = @CONTACTIDNO1,
		[CONTACTIDNO2] = @CONTACTIDNO2,
		[SUBSCRIPTIONID] = @SUBSCRIPTIONID,
		[ACTIVE] = @ACTIVE,
		[RATE1PERHOUR] = @RATE1PERHOUR,
		[RATE2PERHOUR] = @RATE2PERHOUR,
		[RATE3PERHOUR] = @RATE3PERHOUR,
		[RATE4PERHOUR] = @RATE4PERHOUR,
		[RATE1TEXT] = @RATE1TEXT,
		[RATE2TEXT] = @RATE2TEXT,
		[RATE3TEXT] = @RATE3TEXT,
		[RATE4TEXT] = @RATE4TEXT
	WHERE
		[CUSTOMERID] = @CUSTOMERID
GO
