SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Deletes a record from the 'SUBSCRIPTIONSEXT' table using the primary key value.
CREATE PROCEDURE [dbo].[_SUBSCRIPTIONSEXT_DeleteByPrimaryKey]
	@SUBSCRIPTIONID int
AS
	DELETE FROM [dbo].[SUBSCRIPTIONSEXT] WHERE
		[SUBSCRIPTIONID] = @SUBSCRIPTIONID
GO
