SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Deletes all records from the 'REPORT_CATALOG' table.
CREATE PROCEDURE [dbo].[_REPORT_CATALOG_DeleteAll]
AS
	DELETE FROM [dbo].[REPORT_CATALOG]
GO
