SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Gets a record from the 'SUBSCRIPTIONSEXT' table using the primary key value.
CREATE PROCEDURE [dbo].[_SUBSCRIPTIONSEXT_GetByPrimaryKey]
	@SUBSCRIPTIONID int
AS
	SELECT * FROM [dbo].[SUBSCRIPTIONSEXT] WHERE
		[SUBSCRIPTIONID] = @SUBSCRIPTIONID
GO
