SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

-- Deletes all records from the 'CUSTOMERSXFACILITYUSER' table.
CREATE PROCEDURE [dbo].[_CUSTOMERSXFACILITYUSER_DeleteAll]
AS
	DELETE FROM [dbo].[CUSTOMERSXFACILITYUSER]
GO
