SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE dbo.cmsTREEAddNode
(
	@POSNODE	        INT,
	@ADDNODE			CHAR(50), 
	@CATEGORYID         INT 
)
AS

SET NOCOUNT ON

DECLARE @theRight	INT

SELECT @theRight=TREERN FROM [CASESTREE] WHERE TREEID=@POSNODE

UPDATE [CASESTREE] SET [TREERN] = TREERN+2
WHERE TREERN > @theRIGHT-1


UPDATE [CASESTREE] SET [TREELN] = TREELN+2
WHERE TREELN > @theRIGHT

INSERT INTO CASESTREE(CATEGORYID,NODENAME,TREELN,TREERN) VALUES (@CATEGORYID,@ADDNODE,@theRight,@theRight+1)

GO
