SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Gets all records from the 'LEDGERVALUES_OLD' table.
CREATE PROCEDURE [dbo].[_LEDGERVALUES_OLD_GetAll]
AS
	SELECT * FROM [dbo].[LEDGERVALUES_OLD]
GO
