SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Inserts a new record into the 'USERSRIGHTS' table.
CREATE PROCEDURE [dbo].[_USERSRIGHTS_Insert]
	@SUBSCRIPTIONID int,
	@USERID int,
	@CASEID int,
	@ACTIONID int,
	@NOINVITE bit,
	@NOCHANGE bit,
	@NOASSIGN bit,
	@NOASSIGNEE bit,
	@INVISIBLE bit,
	@NOUNINVITE bit,
	@VIEWPRIVATE bit,
	@CHANGEPRIVATE bit,
	@NOCASES bit,
	@NOACTIONS bit,
	@NOANALYSIS bit,
	@NOCUSTOMERS bit,
	@NOSCHEDULES bit,
	@NOMAINTENANCE bit,
	@NOMONITORING bit
AS
	INSERT INTO [dbo].[USERSRIGHTS]
	(
		[SUBSCRIPTIONID],
		[USERID],
		[CASEID],
		[ACTIONID],
		[NOINVITE],
		[NOCHANGE],
		[NOASSIGN],
		[NOASSIGNEE],
		[INVISIBLE],
		[NOUNINVITE],
		[VIEWPRIVATE],
		[CHANGEPRIVATE],
		[NOCASES],
		[NOACTIONS],
		[NOANALYSIS],
		[NOCUSTOMERS],
		[NOSCHEDULES],
		[NOMAINTENANCE],
		[NOMONITORING]
	)
	VALUES
	(
		@SUBSCRIPTIONID,
		@USERID,
		@CASEID,
		@ACTIONID,
		@NOINVITE,
		@NOCHANGE,
		@NOASSIGN,
		@NOASSIGNEE,
		@INVISIBLE,
		@NOUNINVITE,
		@VIEWPRIVATE,
		@CHANGEPRIVATE,
		@NOCASES,
		@NOACTIONS,
		@NOANALYSIS,
		@NOCUSTOMERS,
		@NOSCHEDULES,
		@NOMAINTENANCE,
		@NOMONITORING
	)
	SELECT @@IDENTITY
GO
