SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Gets all records from the 'REPORTSCHEDULELOGS' table.
CREATE PROCEDURE [dbo].[_REPORTSCHEDULELOGS_GetAll]
AS
	SELECT * FROM [dbo].[REPORTSCHEDULELOGS]
GO
