SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Gets all records from the 'ALLCUSTOMERFACILITIES' table.
CREATE PROCEDURE [dbo].[_ALLCUSTOMERFACILITIES_GetAll]
AS
	SELECT * FROM [dbo].[ALLCUSTOMERFACILITIES]
GO
