SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Deletes all records from the 'CUSTOMERSXUSERS' table.
CREATE PROCEDURE [dbo].[_CUSTOMERSXUSERS_DeleteAll]
AS
	DELETE FROM [dbo].[CUSTOMERSXUSERS]
GO
