SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Deletes all records from the 'SUBSXTEMPLATES' table.
CREATE PROCEDURE [dbo].[_SUBSXTEMPLATES_DeleteAll]
AS
	DELETE FROM [dbo].[SUBSXTEMPLATES]
GO
