SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Gets a record from the 'TREEATTRIBUTES' table using the primary key value.
CREATE PROCEDURE [dbo].[_TREEATTRIBUTES_GetByPrimaryKey]
	@ATTID int
AS
	SELECT * FROM [dbo].[TREEATTRIBUTES] WHERE
		[ATTID] = @ATTID
GO
