SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Gets all records from the 'REPORTSCHEDULECONFIG' table.
CREATE PROCEDURE [dbo].[_REPORTSCHEDULECONFIG_GetAll]
AS
	SELECT * FROM [dbo].[REPORTSCHEDULECONFIG]
GO
