SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE dbo.cmsRptSchedule
AS
SET NOCOUNT ON
  
SELECT RS.[REPORTSCHEDULEID],
       R.[DESCRIPTION],
       (SELECT TOP 1 
        S.[DESCRIPTION]
        FROM [SUBSCRIPTIONS] AS S
        WHERE S.[SUBSCRIPTIONID] = RS.[SUBSCRIPTIONID]) AS [OWNER],
       RS.[LASTRUN],
       RS.[NEXTRUN],
       RS.[UPDATED]
  FROM [REPORTSCHEDULES] AS RS
  INNER JOIN [REPORTS] AS R ON R.[ID] = RS.[REPORTID]
  WHERE R.[ACTIVE] = 1

GO
