SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Gets all records from the 'TMLOCALIZATIONSCOPY' table.
CREATE PROCEDURE [dbo].[_TMLOCALIZATIONSCOPY_GetAll]
AS
	SELECT * FROM [dbo].[TMLOCALIZATIONSCOPY]
GO
