SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Deletes all records from the 'CASESTREETERMS' table.
CREATE PROCEDURE [dbo].[_CASESTREETERMS_DeleteAll]
AS
	DELETE FROM [dbo].[CASESTREETERMS]
GO
