SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[cmsGetScheduleReport] 
(
	@SubscriptionID INTEGER=0
)
AS
SET NOCOUNT ON

SELECT R.[ID],
       R.[DESCRIPTION],
       R.[NAME],
       R.[PARAMETERS],
       R.[ACTIVE],
       R.[REPORTTYPE],
       R.[SUBSCRIPTIONID],
       ISNULL(RS.[REPORTID],0) AS [REPORTID],
       ISNULL(RS.[REPORTSCHEDULEID],0) AS [REPORTSCHEDULEID],
       RS.[LASTRUN],
       RS.[NEXTRUN],
       RS.[UPDATED],
       S.[TMROLE],
       S.[DESCRIPTION] AS [GROUPDESCRIPTION]
  FROM [REPORTS] AS R
  LEFT JOIN [REPORTSCHEDULES] AS RS ON RS.[REPORTID] = R.[ID] AND (RS.[SUBSCRIPTIONID] = R.[SUBSCRIPTIONID])
  INNER JOIN [SUBSCRIPTIONS] AS S ON S.[SUBSCRIPTIONID] = R.[SUBSCRIPTIONID]
 WHERE (R.[ACTIVE] = 1
   AND (@SubscriptionID = 0 OR @SubscriptionID = R.[SUBSCRIPTIONID]))

GO
