SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

-- Gets all records from the 'CATEGORIESBASEOLD' table.
CREATE PROCEDURE [dbo].[_CATEGORIESBASEOLD_GetAll]
AS
	SELECT * FROM [dbo].[CATEGORIESBASEOLD]
GO
