SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Deletes all records from the 'REPORTSCHEDULECONFIG' table.
CREATE PROCEDURE [dbo].[_REPORTSCHEDULECONFIG_DeleteAll]
AS
	DELETE FROM [dbo].[REPORTSCHEDULECONFIG]
GO
