SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

-- Gets all records from the 'BASEACTIONINVITES' table.
CREATE PROCEDURE [dbo].[_BASEACTIONINVITES_GetAll]
AS
	SELECT * FROM [dbo].[BASEACTIONINVITES]
GO
