SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE dbo.cmsUpdScheduleReportSubscription 
(
	@ReportScheduleID INTEGER=0
)
AS
SET NOCOUNT ON

SELECT R.[ID],
       R.[DESCRIPTION],
       R.[NAME],
       R.[PARAMETERS],
       R.[ACTIVE],
       R.[REPORTTYPE],
       S.[SUBSCRIPTIONID],
       S.[REPORTID],
       S.[REPORTSCHEDULEID]
  FROM [REPORTSCHEDULES] AS S
 INNER JOIN [REPORTS] AS R ON R.[ID] = S.[REPORTID]
 WHERE S.[REPORTSCHEDULEID] = @ReportScheduleID

GO
