SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Updates a record in the 'USERSRIGHTS' table.
CREATE PROCEDURE [dbo].[_USERSRIGHTS_Update]
	-- The rest of writeable parameters
	@SUBSCRIPTIONID int,
	@USERID int,
	@CASEID int,
	@ACTIONID int,
	@NOINVITE bit,
	@NOCHANGE bit,
	@NOASSIGN bit,
	@NOASSIGNEE bit,
	@INVISIBLE bit,
	@NOUNINVITE bit,
	@VIEWPRIVATE bit,
	@CHANGEPRIVATE bit,
	@NOCASES bit,
	@NOACTIONS bit,
	@NOANALYSIS bit,
	@NOCUSTOMERS bit,
	@NOSCHEDULES bit,
	@NOMAINTENANCE bit,
	@NOMONITORING bit,
	-- Primary key parameters
	@ID int
AS
	UPDATE [dbo].[USERSRIGHTS] SET
		[SUBSCRIPTIONID] = @SUBSCRIPTIONID,
		[USERID] = @USERID,
		[CASEID] = @CASEID,
		[ACTIONID] = @ACTIONID,
		[NOINVITE] = @NOINVITE,
		[NOCHANGE] = @NOCHANGE,
		[NOASSIGN] = @NOASSIGN,
		[NOASSIGNEE] = @NOASSIGNEE,
		[INVISIBLE] = @INVISIBLE,
		[NOUNINVITE] = @NOUNINVITE,
		[VIEWPRIVATE] = @VIEWPRIVATE,
		[CHANGEPRIVATE] = @CHANGEPRIVATE,
		[NOCASES] = @NOCASES,
		[NOACTIONS] = @NOACTIONS,
		[NOANALYSIS] = @NOANALYSIS,
		[NOCUSTOMERS] = @NOCUSTOMERS,
		[NOSCHEDULES] = @NOSCHEDULES,
		[NOMAINTENANCE] = @NOMAINTENANCE,
		[NOMONITORING] = @NOMONITORING
	WHERE
		[ID] = @ID
GO
