SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Inserts a new record into the 'REPORTSCHEDULELOGS' table.
CREATE PROCEDURE [dbo].[_REPORTSCHEDULELOGS_Insert]
	@REPORTSCHEDULEID int,
	@LOGTIME datetime,
	@LOG nvarchar(max)
AS
	INSERT INTO [dbo].[REPORTSCHEDULELOGS]
	(
		[REPORTSCHEDULEID],
		[LOGTIME],
		[LOG]
	)
	VALUES
	(
		@REPORTSCHEDULEID,
		@LOGTIME,
		@LOG
	)
	SELECT @@IDENTITY
GO
