SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Inserts a new record into the 'CUSTOMERS' table.
CREATE PROCEDURE [dbo].[_CUSTOMERS_Insert]
	@PERSONID int,
	@USERID int,
	@REGNO nvarchar(50),
	@COMPANYCODE nchar(10),
	@COMPANYNAME nvarchar(70),
	@ADDRESSLINE1 nchar(70),
	@ADDRESSLINE2 nchar(70),
	@CITY nchar(70),
	@POSTCODE nchar(20),
	@COUNTRY nchar(70),
	@TELEPHONE nchar(30),
	@EMAIL nchar(30),
	@CONTACTCARDTYPE nvarchar(50),
	@CONTACTCARDNO nvarchar(50),
	@CONTACTIDNO1 nvarchar(50),
	@CONTACTIDNO2 nvarchar(50),
	@SUBSCRIPTIONID int,
	@ACTIVE bit,
	@RATE1PERHOUR numeric(18,3),
	@RATE2PERHOUR numeric(18,3),
	@RATE3PERHOUR numeric(18,3),
	@RATE4PERHOUR numeric(18,3),
	@RATE1TEXT nvarchar(50),
	@RATE2TEXT nvarchar(50),
	@RATE3TEXT nvarchar(50),
	@RATE4TEXT nvarchar(50)
AS
	INSERT INTO [dbo].[CUSTOMERS]
	(
		[PERSONID],
		[USERID],
		[REGNO],
		[COMPANYCODE],
		[COMPANYNAME],
		[ADDRESSLINE1],
		[ADDRESSLINE2],
		[CITY],
		[POSTCODE],
		[COUNTRY],
		[TELEPHONE],
		[EMAIL],
		[CONTACTCARDTYPE],
		[CONTACTCARDNO],
		[CONTACTIDNO1],
		[CONTACTIDNO2],
		[SUBSCRIPTIONID],
		[ACTIVE],
		[RATE1PERHOUR],
		[RATE2PERHOUR],
		[RATE3PERHOUR],
		[RATE4PERHOUR],
		[RATE1TEXT],
		[RATE2TEXT],
		[RATE3TEXT],
		[RATE4TEXT]
	)
	VALUES
	(
		@PERSONID,
		@USERID,
		@REGNO,
		@COMPANYCODE,
		@COMPANYNAME,
		@ADDRESSLINE1,
		@ADDRESSLINE2,
		@CITY,
		@POSTCODE,
		@COUNTRY,
		@TELEPHONE,
		@EMAIL,
		@CONTACTCARDTYPE,
		@CONTACTCARDNO,
		@CONTACTIDNO1,
		@CONTACTIDNO2,
		@SUBSCRIPTIONID,
		@ACTIVE,
		@RATE1PERHOUR,
		@RATE2PERHOUR,
		@RATE3PERHOUR,
		@RATE4PERHOUR,
		@RATE1TEXT,
		@RATE2TEXT,
		@RATE3TEXT,
		@RATE4TEXT
	)
	SELECT @@IDENTITY
GO
