SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Gets all records from the 'SUBSCRIPTIONCODES' table.
CREATE PROCEDURE [dbo].[_SUBSCRIPTIONCODES_GetAll]
AS
	SELECT * FROM [dbo].[SUBSCRIPTIONCODES]
GO
