SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Inserts a new record into the 'USERS' table.
CREATE PROCEDURE [dbo].[_USERS_Insert]
	@UserId int,
	@SUBSCRIPTIONID int,
	@GROUPID int,
	@OFFSET numeric(4,2),
	@_CMSOrganizationBelongsTO int,
	@FirstName varchar(50),
	@LastName varchar(50),
	@UserName nchar(50),
	@DNNNAME nvarchar(50),
	@DNN_USERID nvarchar(50),
	@PassWord nvarchar(50),
	@Email nvarchar(50),
	@Admin bit,
	@Active bit,
	@LastUpdate datetime,
	@External bit,
	@Guest bit,
	@Created datetime,
	@Country nvarchar(50),
	@LastLogin datetime,
	@LASTONLINE datetime,
	@LASTTIMEOUT datetime,
	@LASTLOGOUT datetime,
	@SkypeHandle nvarchar(max),
	@ManagerName nvarchar(max),
	@ManagerEmail nvarchar(max),
	@Telephone nvarchar(max),
	@Fax nvarchar(max),
	@MobilePhone nvarchar(max),
	@Address1 nvarchar(max),
	@Address2 nvarchar(max),
	@City nvarchar(max),
	@ZipCode nvarchar(max),
	@CountryID int,
	@DepartmentID int,
	@Confirmation datetime,
	@SkypeStatus int,
	@WebStatus int,
	@Mood nchar(50),
	@IMProviderID int,
	@IMUserName nvarchar(50),
	@IMPassword nvarchar(50),
	@CodeCountry nchar(2),
	@CodeLocale nchar(5),
	@CodeCompany nvarchar(50),
	@CodeLocation nvarchar(50),
	@CodeTheme nvarchar(50),
	@CodeOrganization nvarchar(50),
	@PARENTID int
AS
	INSERT INTO [dbo].[USERS]
	(
		[UserId],
		[SUBSCRIPTIONID],
		[GROUPID],
		[OFFSET],
		[_CMSOrganizationBelongsTO],
		[FirstName],
		[LastName],
		[UserName],
		[DNNNAME],
		[DNN_USERID],
		[PassWord],
		[Email],
		[Admin],
		[Active],
		[LastUpdate],
		[External],
		[Guest],
		[Created],
		[Country],
		[LastLogin],
		[LASTONLINE],
		[LASTTIMEOUT],
		[LASTLOGOUT],
		[SkypeHandle],
		[ManagerName],
		[ManagerEmail],
		[Telephone],
		[Fax],
		[MobilePhone],
		[Address1],
		[Address2],
		[City],
		[ZipCode],
		[CountryID],
		[DepartmentID],
		[Confirmation],
		[SkypeStatus],
		[WebStatus],
		[Mood],
		[IMProviderID],
		[IMUserName],
		[IMPassword],
		[CodeCountry],
		[CodeLocale],
		[CodeCompany],
		[CodeLocation],
		[CodeTheme],
		[CodeOrganization],
		[PARENTID]
	)
	VALUES
	(
		@UserId,
		@SUBSCRIPTIONID,
		@GROUPID,
		@OFFSET,
		@_CMSOrganizationBelongsTO,
		@FirstName,
		@LastName,
		@UserName,
		@DNNNAME,
		@DNN_USERID,
		@PassWord,
		@Email,
		@Admin,
		@Active,
		@LastUpdate,
		@External,
		@Guest,
		@Created,
		@Country,
		@LastLogin,
		@LASTONLINE,
		@LASTTIMEOUT,
		@LASTLOGOUT,
		@SkypeHandle,
		@ManagerName,
		@ManagerEmail,
		@Telephone,
		@Fax,
		@MobilePhone,
		@Address1,
		@Address2,
		@City,
		@ZipCode,
		@CountryID,
		@DepartmentID,
		@Confirmation,
		@SkypeStatus,
		@WebStatus,
		@Mood,
		@IMProviderID,
		@IMUserName,
		@IMPassword,
		@CodeCountry,
		@CodeLocale,
		@CodeCompany,
		@CodeLocation,
		@CodeTheme,
		@CodeOrganization,
		@PARENTID
	)
	SELECT @@IDENTITY
GO
