SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Gets all records from the 'MYCHATINVITESNEW' table.
CREATE PROCEDURE [dbo].[_MYCHATINVITESNEW_GetAll]
AS
	SELECT * FROM [dbo].[MYCHATINVITESNEW]
GO
