SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Inserts a new record into the 'FUSIONREPORTS' table.
CREATE PROCEDURE [dbo].[_FUSIONREPORTS_Insert]
	@TITLE nvarchar(50),
	@DESCRIPTION nvarchar(max),
	@SQL nvarchar(max),
	@FUSIONKEY nvarchar(50),
	@ACTIVE bit,
	@DATECREATED datetime,
	@DATEUPDATED datetime,
	@ANIMATION bit,
	@SHOWNAMES bit,
	@SHOWPERCENTAGEVALUES bit,
	@GRAPHTYPE nvarchar(50)
AS
	INSERT INTO [dbo].[FUSIONREPORTS]
	(
		[TITLE],
		[DESCRIPTION],
		[SQL],
		[FUSIONKEY],
		[ACTIVE],
		[DATECREATED],
		[DATEUPDATED],
		[ANIMATION],
		[SHOWNAMES],
		[SHOWPERCENTAGEVALUES],
		[GRAPHTYPE]
	)
	VALUES
	(
		@TITLE,
		@DESCRIPTION,
		@SQL,
		@FUSIONKEY,
		@ACTIVE,
		@DATECREATED,
		@DATEUPDATED,
		@ANIMATION,
		@SHOWNAMES,
		@SHOWPERCENTAGEVALUES,
		@GRAPHTYPE
	)
	SELECT @@IDENTITY
GO
