SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE dbo.cmsGetCaseQueryOther @SubscriptionID INTEGER=0
AS
SET NOCOUNT ON

	SELECT NODENAME,
	       NODEVALUE,
	       TREELEVEL,
	       NODETAG
	FROM CASESTREE
	WHERE CATEGORYID = 1300 -- Incident Type
	AND ACTIVE = 1
	AND NODETAG = 'OTH' -- Other Type
	AND TREELEVEL = 3
	ORDER BY NODENAME

GO
