SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

-- Deletes a record from the 'CUSTOMERSXFACILITYUSER' table using the primary key value.
CREATE PROCEDURE [dbo].[_CUSTOMERSXFACILITYUSER_DeleteByPrimaryKey]
	@ID int
AS
	DELETE FROM [dbo].[CUSTOMERSXFACILITYUSER] WHERE
		[ID] = @ID
GO
