SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE dbo.cmsGetCaseQueryCountry @SubscriptionID INTEGER=0
AS
SET NOCOUNT ON

	SELECT DISTINCT CASE WHEN CHARINDEX('.',TMROLE) > 1
	                     THEN SUBSTRING(TMROLE, (CHARINDEX('.',TMROLE) + 1), (LEN(TMROLE) - CHARINDEX('.',TMROLE)))
	                     ELSE TMROLE END AS CountryCode,
	                     NODENAME AS CountryName
	FROM SUBSCRIPTIONS AS S WITH (NOLOCK)
	INNER JOIN CASESTREE AS T WITH (NOLOCK) ON T.CATEGORYID = 1603
	                     AND T.NODETEXT = SUBSTRING(TMROLE, (CHARINDEX('.',TMROLE) + 1), (LEN(TMROLE) - CHARINDEX('.',TMROLE)))
	WHERE LEN(LTRIM(RTRIM(TMROLE))) > 1
	  AND LTRIM(RTRIM(TMROLE)) <> 'Help'
	ORDER BY CountryName

GO
