SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

-- Gets all records from the 'CUSTOMERSXFACILITYUSER' table.
CREATE PROCEDURE [dbo].[_CUSTOMERSXFACILITYUSER_GetAll]
AS
	SELECT * FROM [dbo].[CUSTOMERSXFACILITYUSER]
GO
