SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Gets all records from the 'ALLSUBSCRIPTIONS' table.
CREATE PROCEDURE [dbo].[_ALLSUBSCRIPTIONS_GetAll]
AS
	SELECT * FROM [dbo].[ALLSUBSCRIPTIONS]
GO
