SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Gets all records from the 'ALLCUSTOMERUSERS' table.
CREATE PROCEDURE [dbo].[_ALLCUSTOMERUSERS_GetAll]
AS
	SELECT * FROM [dbo].[ALLCUSTOMERUSERS]
GO
