SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE dbo.cmsUpdSchedule 
                 @ReportScheduleID INTEGER,
                 @ReportID INTEGER,
                 @SubscriptionID INTEGER,
                 @Start DATE,
                 @Stop DATE,
                 @ScheduleEnd BIT,
                 @Interval CHAR(1),
                 @IntervalHourRepeat BIT,
                 @IntervalDayDays BIT,
                 @IntervalDayRepeat BIT,
                 @IntervalMonthWeek BIT,
                 @IntervalMonthDay BIT,
                 @RepeatWeeks INTEGER,
                 @RepeatDays INTEGER,
                 @RepeatHours INTEGER,
                 @RepeatMinutes INTEGER,
                 @StartHours INTEGER,
                 @StartMinutes INTEGER,
                 @Render VARCHAR(10),
                 @Sun BIT,
                 @Mon BIT,
                 @Tue BIT,
                 @Wed BIT,
                 @Thu BIT,
                 @Fri BIT,
                 @Sat BIT,
                 @Jan BIT,
                 @Feb BIT,
                 @Mar BIT,
                 @Apr BIT,
                 @May BIT,
                 @Jun BIT,
                 @Jul BIT,
                 @Aug BIT,
                 @Sep BIT,
                 @Oct BIT,
                 @Nov BIT,
                 @Dec BIT,
                 @Week VARCHAR(10),
                 @Days VARCHAR(50)
AS
SET NOCOUNT ON

IF @ReportScheduleID > 0
BEGIN
	UPDATE [REPORTSCHEDULES]
	   SET [START] = @Start,
	       [STOP] = @Stop,
	       [SCHEDULEEND] = @ScheduleEnd,
           [INTERVAL] = @Interval,
           [INTERVALHOURREPEAT] = @IntervalHourRepeat,
           [INTERVALDAYDAYS] = @IntervalDayDays,
           [INTERVALDAYREPEAT] = @IntervalDayRepeat,
           [INTERVALMONTHWEEK] = @IntervalMonthWeek,
           [INTERVALMONTHDAY] = @IntervalMonthDay,
           [REPEATWEEKS] = @RepeatWeeks,
           [REPEATDAYS] = @RepeatDays,
           [REPEATHOURS] = @RepeatHours,
           [REPEATMINUTES] = @RepeatMinutes,
           [STARTHOURS] = @StartHours,
           [STARTMINUTES] = @StartMinutes,
           [RENDER] = @Render,
           [SUN] = @Sun,
           [MON] = @Mon,
           [TUE] = @Tue,
           [WED] = @Wed,
           [THU] = @Thu,
           [FRI] = @Fri,
           [SAT] = @Sat,
           [JAN] = @Jan,
           [FEB] = @Feb,
           [MAR] = @Mar,
           [APR] = @Apr,
           [MAY] = @May,
           [JUN] = @Jun,
           [JUL] = @Jul,
           [AUG] = @Aug,
           [SEP] = @Sep,
           [OCT] = @Oct,
           [NOV] = @Nov,
           [DEC] = @Dec,
           [WEEK] = @Week,
           [DAYS] = @Days
     WHERE [REPORTSCHEDULEID] = @ReportScheduleID
END
ELSE
BEGIN
   INSERT INTO [REPORTSCHEDULES] ([REPORTID],
                                  [SUBSCRIPTIONID],
                                  [START],
                                  [STOP],
                                  [SCHEDULEEND],
                                  [INTERVAL],
                                  [INTERVALHOURREPEAT],
                                  [INTERVALDAYDAYS],
                                  [INTERVALDAYREPEAT],
                                  [INTERVALMONTHWEEK],
                                  [INTERVALMONTHDAY],
                                  [REPEATWEEKS],
                                  [REPEATDAYS],
                                  [REPEATHOURS],
                                  [REPEATMINUTES],
                                  [STARTHOURS],
                                  [STARTMINUTES],
                                  [RENDER],
                                  [SUN],
                                  [MON],
                                  [TUE],
                                  [WED],
                                  [THU],
                                  [FRI],
                                  [SAT],
                                  [JAN],
                                  [FEB],
                                  [MAR],
                                  [APR],
                                  [MAY],
                                  [JUN],
                                  [JUL],
                                  [AUG],
                                  [SEP],
                                  [OCT],
                                  [NOV],
                                  [DEC],
                                  [WEEK],
                                  [DAYS])
                          VALUES (@ReportID,
                                  @SubscriptionID,
                                  @Start,
                                  @Stop,
                                  @ScheduleEnd,
                                  @Interval,
                                  @IntervalHourRepeat,
                                  @IntervalDayDays,
                                  @IntervalDayRepeat,
                                  @IntervalMonthWeek,
                                  @IntervalMonthDay,
                                  @RepeatWeeks,
                                  @RepeatDays,
                                  @RepeatHours,
                                  @RepeatMinutes,
                                  @StartHours,
                                  @StartMinutes,
                                  @Render,
                                  @Sun,
                                  @Mon,
                                  @Tue,
                                  @Wed,
                                  @Thu,
                                  @Fri,
                                  @Sat,
                                  @Jan,
                                  @Feb,
                                  @Mar,
                                  @Apr,
                                  @May,
                                  @Jun,
                                  @Jul,
                                  @Aug,
                                  @Sep,
                                  @Oct,
                                  @Nov,
                                  @Dec,
                                  @Week,
                                  @Days)
   SET @ReportScheduleID = SCOPE_IDENTITY()
END

EXECUTE cmsSchedule_fnUpdate @ReportScheduleID, 'U'

SELECT [REPORTSCHEDULEID],
       [LASTRUN],
       [NEXTRUN]
  FROM [REPORTSCHEDULES]
 WHERE [REPORTSCHEDULEID] = @ReportScheduleID

GO
