SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Updates a record in the 'CABINET' table.
CREATE PROCEDURE [dbo].[_CABINET_Update]
	-- The rest of writeable parameters
	@TITLE nvarchar(200),
	@DESCRIPTION nvarchar(70),
	@CONTENTID int,
	@ITEMTYPE nchar(16),
	@CASEID int,
	@ACTIONID int,
	@ITEMSUBTYPE nchar(16),
	@ITEMTYPENO int,
	@ITEMSUBTYPENO int,
	@PARENTID int,
	@LASTUPDATED datetime,
	@UPDATEDBY nvarchar(70),
	@CREATED datetime,
	@CREATEDBY nvarchar(70),
	@ACTIVE bit,
	@LISTORDER int,
	@CREATEDBYUSERID int,
	@UPDATEDBYUSERID int,
	@PRIVACYID int,
	@PRIVACY nchar(10),
	@IsPrivate bit,
	-- Primary key parameters
	@CABINETID int
AS
	UPDATE [dbo].[CABINET] SET
		[TITLE] = @TITLE,
		[DESCRIPTION] = @DESCRIPTION,
		[CONTENTID] = @CONTENTID,
		[ITEMTYPE] = @ITEMTYPE,
		[CASEID] = @CASEID,
		[ACTIONID] = @ACTIONID,
		[ITEMSUBTYPE] = @ITEMSUBTYPE,
		[ITEMTYPENO] = @ITEMTYPENO,
		[ITEMSUBTYPENO] = @ITEMSUBTYPENO,
		[PARENTID] = @PARENTID,
		[LASTUPDATED] = @LASTUPDATED,
		[UPDATEDBY] = @UPDATEDBY,
		[CREATED] = @CREATED,
		[CREATEDBY] = @CREATEDBY,
		[ACTIVE] = @ACTIVE,
		[LISTORDER] = @LISTORDER,
		[CREATEDBYUSERID] = @CREATEDBYUSERID,
		[UPDATEDBYUSERID] = @UPDATEDBYUSERID,
		[PRIVACYID] = @PRIVACYID,
		[PRIVACY] = @PRIVACY,
		[IsPrivate] = @IsPrivate
	WHERE
		[CABINETID] = @CABINETID
GO
