SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Gets all records from the 'SUBSCRIPTIONTHEMES' table.
CREATE PROCEDURE [dbo].[_SUBSCRIPTIONTHEMES_GetAll]
AS
	SELECT * FROM [dbo].[SUBSCRIPTIONTHEMES]
GO
