SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Updates a record in the 'CASESTREETERMS' table.
CREATE PROCEDURE [dbo].[_CASESTREETERMS_Update]
	-- The rest of writeable parameters
	@TREEID int,
	@CATEGORYID int,
	@UPDATEBYID int,
	@UPDATEDBY nchar(30),
	@LASTUPDATED datetime,
	@BASETERM nvarchar(max),
	@TEXT1 nvarchar(max),
	@TEXT2 nvarchar(max),
	@TEXT3 nvarchar(max),
	@TEXT4 nvarchar(max),
	@TEXT5 nvarchar(max),
	@TEXT6 nvarchar(max),
	@TEXT7 nvarchar(max),
	@TEXT8 nvarchar(max),
	@ENUSTR nvarchar(max),
	@DEDETR nvarchar(max),
	@THTHTR nvarchar(max),
	@ENUSTP nvarchar(max),
	@DEDETP nvarchar(max),
	@DEDETPTIP nvarchar(50),
	@THTHTP nvarchar(max),
	@EnUSTPTIP nvarchar(max),
	@ENGBTP nvarchar(max),
	@ENGBTPTIP nvarchar(max),
	@THTHTPTIP nvarchar(max),
	@NLNLTP nvarchar(max),
	@NLNLTPTIP nvarchar(max),
	@TRTRTP nvarchar(50),
	@TRTRTPTIP nvarchar(50),
	@GBGBTP nvarchar(max),
	@GBGBTPTIP nvarchar(max),
	@HEILTP nvarchar(max),
	@HEILTPTIP nvarchar(max),
	@AREGTP nvarchar(max),
	@AREGTPTIP nvarchar(max),
	@ZHCNTP nvarchar(max),
	@ZHCNTPTIP nvarchar(max),
	@VIVNTP nvarchar(max),
	@VIVNTPTIP nvarchar(max),
	@JAJPTP nvarchar(max),
	@JAJPTPTIP nvarchar(max),
	@ENNLTP nvarchar(max),
	@ENNLTPTIP nvarchar(max),
	@JAJATP nvarchar(max),
	@JAJATPTIP nvarchar(max),
	@ENENTP nvarchar(max),
	@ENENTPTIP nvarchar(max),
	@FRFRTP nvarchar(max),
	@FRFRTPTIP nvarchar(max),
	-- Primary key parameters
	@ID int
AS
	UPDATE [dbo].[CASESTREETERMS] SET
		[TREEID] = @TREEID,
		[CATEGORYID] = @CATEGORYID,
		[UPDATEBYID] = @UPDATEBYID,
		[UPDATEDBY] = @UPDATEDBY,
		[LASTUPDATED] = @LASTUPDATED,
		[BASETERM] = @BASETERM,
		[TEXT1] = @TEXT1,
		[TEXT2] = @TEXT2,
		[TEXT3] = @TEXT3,
		[TEXT4] = @TEXT4,
		[TEXT5] = @TEXT5,
		[TEXT6] = @TEXT6,
		[TEXT7] = @TEXT7,
		[TEXT8] = @TEXT8,
		[ENUSTR] = @ENUSTR,
		[DEDETR] = @DEDETR,
		[THTHTR] = @THTHTR,
		[ENUSTP] = @ENUSTP,
		[DEDETP] = @DEDETP,
		[DEDETPTIP] = @DEDETPTIP,
		[THTHTP] = @THTHTP,
		[enUSTPTIP] = @EnUSTPTIP,
		[ENGBTP] = @ENGBTP,
		[ENGBTPTIP] = @ENGBTPTIP,
		[THTHTPTIP] = @THTHTPTIP,
		[NLNLTP] = @NLNLTP,
		[NLNLTPTIP] = @NLNLTPTIP,
		[TRTRTP] = @TRTRTP,
		[TRTRTPTIP] = @TRTRTPTIP,
		[GBGBTP] = @GBGBTP,
		[GBGBTPTIP] = @GBGBTPTIP,
		[HEILTP] = @HEILTP,
		[HEILTPTIP] = @HEILTPTIP,
		[AREGTP] = @AREGTP,
		[AREGTPTIP] = @AREGTPTIP,
		[ZHCNTP] = @ZHCNTP,
		[ZHCNTPTIP] = @ZHCNTPTIP,
		[VIVNTP] = @VIVNTP,
		[VIVNTPTIP] = @VIVNTPTIP,
		[JAJPTP] = @JAJPTP,
		[JAJPTPTIP] = @JAJPTPTIP,
		[ENNLTP] = @ENNLTP,
		[ENNLTPTIP] = @ENNLTPTIP,
		[JAJATP] = @JAJATP,
		[JAJATPTIP] = @JAJATPTIP,
		[ENENTP] = @ENENTP,
		[ENENTPTIP] = @ENENTPTIP,
		[FRFRTP] = @FRFRTP,
		[FRFRTPTIP] = @FRFRTPTIP
	WHERE
		[ID] = @ID
GO
