SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Gets a record from the 'LISTHEADERS' table using the primary key value.
CREATE PROCEDURE [dbo].[_LISTHEADERS_GetByPrimaryKey]
	@LISTHEADERID int
AS
	SELECT * FROM [dbo].[LISTHEADERS] WHERE
		[LISTHEADERID] = @LISTHEADERID
GO
