SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO


CREATE PROCEDURE [dbo].[cmsGetScheduleParameters] 
(
	@ReportID INTEGER=0,
	@ReportScheduleID INTEGER=0
)
AS
SET NOCOUNT ON

DECLARE @COUNT INTEGER
DECLARE @PARAMETERS VARCHAR(1000)
DECLARE @PARAMETERNAME VARCHAR(1000)
DECLARE @BEGIN INTEGER
DECLARE @END INTEGER
DECLARE @FINISH INTEGER
/*
IF @ReportID > 0 
AND NOT EXISTS(SELECT [PARAMETERNAME] FROM [REPORTSCHEDULEPARAMETERS] WHERE [REPORTSCHEDULEID] = @ReportScheduleID)
BEGIN
   SET @PARAMETERS = (SELECT [PARAMETERS] FROM [REPORTS] WHERE [ID] = @ReportID)
   SET @PARAMETERS = REPLACE(@PARAMETERS,SPACE(1),'')
   SET @PARAMETERS = REPLACE(@PARAMETERS,';',',')
   SET @PARAMETERS = REPLACE(@PARAMETERS,'|',',')
   SET @PARAMETERS = REPLACE(@PARAMETERS,',,',',')
   IF LEN(@PARAMETERS) > 0
   BEGIN
      IF NOT EXISTS(SELECT [PARAMETERNAME] FROM [REPORTSCHEDULEPARAMETERS] WHERE [REPORTSCHEDULEID] = @ReportScheduleID)
      BEGIN
         SET @PARAMETERS = @PARAMETERS + ','
         SET @BEGIN = 1
         SET @END = 0
         SET @FINISH = LEN(@PARAMETERS)
         WHILE @END < @FINISH
         BEGIN
            SET @END = CHARINDEX(',',@PARAMETERS,@BEGIN)
            SET @PARAMETERNAME = SUBSTRING(@PARAMETERS,@BEGIN,(@END - @BEGIN))
            SET @BEGIN = @END + 1
            INSERT INTO [REPORTSCHEDULEPARAMETERS] ([REPORTSCHEDULEID], [PARAMETERNAME])
                                            VALUES (@ReportScheduleID, @PARAMETERNAME)
         END
      END
   END
END
*/
SET @COUNT = ISNULL((SELECT COUNT(*) FROM [REPORTSCHEDULEPARAMETERS]
                                     WHERE [REPORTSCHEDULEID] = @ReportScheduleID),0)
SELECT [REPORTSCHEDULEPARAMETERID] AS [ID],
       [PARAMETERNAME] AS [NAME],
       [PARAMETERVALUE] AS [VALUE],
       @COUNT AS [COUNT]
  FROM [REPORTSCHEDULEPARAMETERS]
 WHERE [REPORTSCHEDULEID] = @ReportScheduleID


GO
