SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE dbo.cmsGetCaseQueryCompany @SubscriptionID INTEGER=0
AS
SET NOCOUNT ON

	SELECT DISTINCT CASE WHEN CHARINDEX('.',TMROLE) > 1
	                     THEN SUBSTRING(TMROLE, 1, CHARINDEX('.',TMROLE) - 1)
	                     ELSE TMROLE END AS Company
	                     /*SUBSCRIPTIONID*/
	FROM SUBSCRIPTIONS WITH (NOLOCK)
	WHERE LEN(LTRIM(RTRIM(TMROLE))) > 1
	  AND LTRIM(RTRIM(TMROLE)) <> 'Help'
	ORDER BY Company

GO
