SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Deletes all records from the 'LEDGERVALUES_OLD' table.
CREATE PROCEDURE [dbo].[_LEDGERVALUES_OLD_DeleteAll]
AS
	DELETE FROM [dbo].[LEDGERVALUES_OLD]
GO
