SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Updates a record in the 'SUBRIGHTS' table.
CREATE PROCEDURE [dbo].[_SUBRIGHTS_Update]
	-- The rest of writeable parameters
	@SUBID int,
	@RIGHTCODE nchar(20),
	@RIGHTTITLE nchar(30),
	@RIGHTDESCRIPTION nchar(80),
	@RIGHTVALUE1 numeric(18,0),
	@RIGHTVALUE2 numeric(18,0),
	@ACTIVE bit,
	-- Primary key parameters
	@SUBRIGHTSID int
AS
	UPDATE [dbo].[SUBRIGHTS] SET
		[SUBID] = @SUBID,
		[RIGHTCODE] = @RIGHTCODE,
		[RIGHTTITLE] = @RIGHTTITLE,
		[RIGHTDESCRIPTION] = @RIGHTDESCRIPTION,
		[RIGHTVALUE1] = @RIGHTVALUE1,
		[RIGHTVALUE2] = @RIGHTVALUE2,
		[ACTIVE] = @ACTIVE
	WHERE
		[SUBRIGHTSID] = @SUBRIGHTSID
GO
