SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Gets a record from the 'CUSTOMERSXFACILITIES' table using the primary key value.
CREATE PROCEDURE [dbo].[_CUSTOMERSXFACILITIES_GetByPrimaryKey]
	@ID int
AS
	SELECT * FROM [dbo].[CUSTOMERSXFACILITIES] WHERE
		[ID] = @ID
GO
