SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE dbo.cmsUpdScheduleLog 
(
	@ReportScheduleID INTEGER,
	@Log VARCHAR(MAX)
)
AS
SET NOCOUNT ON

    INSERT INTO [REPORTSCHEDULELOGS]
                ([REPORTSCHEDULEID], [LOGTIME], [LOG])
         VALUES (@ReportScheduleID, GETDATE(), @Log)
         
    DELETE [REPORTSCHEDULELOGS]
     WHERE [LOGTIME] < DATEADD(Month, -3, GETDATE())

GO
