SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO


CREATE PROCEDURE [dbo].[cmsGetScheduleGroups] 
AS
SET NOCOUNT ON

SELECT [SUBSCRIPTIONID],
       [TMROLE],
       [DESCRIPTION]
FROM [SUBSCRIPTIONS]
WHERE [ACTIVE] = 1 AND SUBSCRIPTIONID <>31 AND SUBSCRIPTIONID<>0
ORDER BY [TMROLE]


GO
