SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Deletes all records from the 'TREEATTRIBUTES' table.
CREATE PROCEDURE [dbo].[_TREEATTRIBUTES_DeleteAll]
AS
	DELETE FROM [dbo].[TREEATTRIBUTES]
GO
