SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE dbo.cmsGetCaseQueryIncidentType @SubscriptionID INTEGER=0
AS
SET NOCOUNT ON

	-- initial query for Type (node tag) because some are at different levels
	SELECT MIN(TREELEVEL) AS TREELEVEL,
	       NODETAG
	INTO #IncidentType
	FROM CASESTREE
	WHERE CATEGORYID = 1300 -- Incident Type
	AND ACTIVE = 1
	AND TREELEVEL > 1
	AND NODETAG <> 'OTH' -- excluding Other Type
	GROUP BY NODETAG

	SELECT CT.NODENAME,
	       CT.NODEVALUE,
	       CT.TREELEVEL,
	       CT.NODETAG
	FROM #IncidentType AS IT
	INNER JOIN CASESTREE AS CT ON CT.TREELEVEL = IT.TREELEVEL AND CT.NODETAG = IT.NODETAG
	WHERE CT.CATEGORYID = 1300 -- Incident Type
	AND CT.ACTIVE = 1
	AND CT.TREELEVEL > 1
	ORDER BY CT.NODENAME

GO
