SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Gets all records from the 'rptTSTIMESHEETSALLREGNO' table.
CREATE PROCEDURE [dbo].[_rptTSTIMESHEETSALLREGNO_GetAll]
AS
	SELECT * FROM [dbo].[rptTSTIMESHEETSALLREGNO]
GO
