SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Inserts a new record into the 'REPORTSCHEDULEPARAMETERS' table.
CREATE PROCEDURE [dbo].[_REPORTSCHEDULEPARAMETERS_Insert]
	@REPORTSCHEDULEID int,
	@PARAMETERNAME nvarchar(50),
	@PARAMETERVALUE nvarchar(3000)
AS
	INSERT INTO [dbo].[REPORTSCHEDULEPARAMETERS]
	(
		[REPORTSCHEDULEID],
		[PARAMETERNAME],
		[PARAMETERVALUE]
	)
	VALUES
	(
		@REPORTSCHEDULEID,
		@PARAMETERNAME,
		@PARAMETERVALUE
	)
	SELECT @@IDENTITY
GO
