SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Updates a record in the 'FUSIONREPORTS' table.
CREATE PROCEDURE [dbo].[_FUSIONREPORTS_Update]
	-- The rest of writeable parameters
	@TITLE nvarchar(50),
	@DESCRIPTION nvarchar(max),
	@SQL nvarchar(max),
	@FUSIONKEY nvarchar(50),
	@ACTIVE bit,
	@DATECREATED datetime,
	@DATEUPDATED datetime,
	@ANIMATION bit,
	@SHOWNAMES bit,
	@SHOWPERCENTAGEVALUES bit,
	@GRAPHTYPE nvarchar(50),
	-- Primary key parameters
	@REPORTID int
AS
	UPDATE [dbo].[FUSIONREPORTS] SET
		[TITLE] = @TITLE,
		[DESCRIPTION] = @DESCRIPTION,
		[SQL] = @SQL,
		[FUSIONKEY] = @FUSIONKEY,
		[ACTIVE] = @ACTIVE,
		[DATECREATED] = @DATECREATED,
		[DATEUPDATED] = @DATEUPDATED,
		[ANIMATION] = @ANIMATION,
		[SHOWNAMES] = @SHOWNAMES,
		[SHOWPERCENTAGEVALUES] = @SHOWPERCENTAGEVALUES,
		[GRAPHTYPE] = @GRAPHTYPE
	WHERE
		[REPORTID] = @REPORTID
GO
