SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Deletes all records from the 'TMLOCALIZATIONS' table.
CREATE PROCEDURE [dbo].[_TMLOCALIZATIONS_DeleteAll]
AS
	DELETE FROM [dbo].[TMLOCALIZATIONS]
GO
