SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Inserts a new record into the 'CUSTOMERSXFACILITIES' table.
CREATE PROCEDURE [dbo].[_CUSTOMERSXFACILITIES_Insert]
	@CUSTOMERID int,
	@TREEID int
AS
	INSERT INTO [dbo].[CUSTOMERSXFACILITIES]
	(
		[CUSTOMERID],
		[TREEID]
	)
	VALUES
	(
		@CUSTOMERID,
		@TREEID
	)
	SELECT @@IDENTITY
GO
