SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Gets all records from the 'REPORTSCHEDULEPARAMETERS' table.
CREATE PROCEDURE [dbo].[_REPORTSCHEDULEPARAMETERS_GetAll]
AS
	SELECT * FROM [dbo].[REPORTSCHEDULEPARAMETERS]
GO
