SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Gets all records from the 'CUSTOMERSXFACILITIES' table.
CREATE PROCEDURE [dbo].[_CUSTOMERSXFACILITIES_GetAll]
AS
	SELECT * FROM [dbo].[CUSTOMERSXFACILITIES]
GO
