SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Inserts a new record into the 'CATEGORIES' table.
CREATE PROCEDURE [dbo].[_CATEGORIES_Insert]
	@CATEGORYID int,
	@TEMPLATEID int,
	@CATNAME nchar(20),
	@DISPLAYNAME nvarchar(50),
	@CATDESC nvarchar(max),
	@CATOF nchar(20),
	@CATOFFIELDNAME nchar(200),
	@ATTNO int,
	@ATTNAME1 nvarchar(50),
	@ATTNAME2 nvarchar(50),
	@ATTNAME3 nvarchar(50),
	@ATTNAME4 nvarchar(50),
	@ATTNAME5 nvarchar(50),
	@ATTNAME6 nvarchar(50),
	@ATTNAMETAG nvarchar(50),
	@ATTNAMETEXT nvarchar(50),
	@ATTNAMEID nvarchar(50),
	@ACTIVE bit,
	@ATTRELNO int,
	@ATTRELID int,
	@RENDERTOLEVEL int,
	@LEAFATLEVEL int,
	@LANGUAGE nvarchar(50),
	@TERMS nvarchar(50),
	@ISGLOBAL bit,
	@ISADMIN bit
AS
	INSERT INTO [dbo].[CATEGORIES]
	(
		[CATEGORYID],
		[TEMPLATEID],
		[CATNAME],
		[DISPLAYNAME],
		[CATDESC],
		[CATOF],
		[CATOFFIELDNAME],
		[ATTNO],
		[ATTNAME1],
		[ATTNAME2],
		[ATTNAME3],
		[ATTNAME4],
		[ATTNAME5],
		[ATTNAME6],
		[ATTNAMETAG],
		[ATTNAMETEXT],
		[ATTNAMEID],
		[ACTIVE],
		[ATTRELNO],
		[ATTRELID],
		[RENDERTOLEVEL],
		[LEAFATLEVEL],
		[LANGUAGE],
		[TERMS],
		[ISGLOBAL],
		[ISADMIN]
	)
	VALUES
	(
		@CATEGORYID,
		@TEMPLATEID,
		@CATNAME,
		@DISPLAYNAME,
		@CATDESC,
		@CATOF,
		@CATOFFIELDNAME,
		@ATTNO,
		@ATTNAME1,
		@ATTNAME2,
		@ATTNAME3,
		@ATTNAME4,
		@ATTNAME5,
		@ATTNAME6,
		@ATTNAMETAG,
		@ATTNAMETEXT,
		@ATTNAMEID,
		@ACTIVE,
		@ATTRELNO,
		@ATTRELID,
		@RENDERTOLEVEL,
		@LEAFATLEVEL,
		@LANGUAGE,
		@TERMS,
		@ISGLOBAL,
		@ISADMIN
	)
	SELECT @@IDENTITY
GO
