SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Deletes all records from the 'CUSTOMERSXFACILITIES' table.
CREATE PROCEDURE [dbo].[_CUSTOMERSXFACILITIES_DeleteAll]
AS
	DELETE FROM [dbo].[CUSTOMERSXFACILITIES]
GO
