SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Deletes all records from the 'CATEGORIESBASE' table.
CREATE PROCEDURE [dbo].[_CATEGORIESBASE_DeleteAll]
AS
	DELETE FROM [dbo].[CATEGORIESBASE]
GO
