SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- Gets all records from the 'rptTSMYHOURVALUES' table.
CREATE PROCEDURE [dbo].[_rptTSMYHOURVALUES_GetAll]
AS
	SELECT * FROM [dbo].[rptTSMYHOURVALUES]
GO
